Azure/azure-webjobs-sdk

- src/Microsoft.Azure.WebJobs.Host/Executors/JobHostContextFactory.cs
Fix for [#511](https://github.com/Azure/azure-webjobs-sdk/issues/511)
> Catch all exceptions when attempting to write WebJobsSdk.marker file

- src/Microsoft.Azure.WebJobs.Host/Indexers/DefaultBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/AsyncCollectorArgumentBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/CloudTableArgumentBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/CollectorArgumentBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/CompositeArgumentBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/CompositeEntityArgumentBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/ITableArgumentBindingExtension.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/ITableArgumentBindingExtensionProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/ITableArgumentBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/ITableEntityArgumentBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/PocoEntityArgumentBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/QueryableArgumentBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/StorageTableArgumentBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/TableArgumentBindingExtensionProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/TableAttributeBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/TableBinding.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/TableEntityArgumentBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/TableEntityBinding.cs
- src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/FunctionalTest.cs
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/TableTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Tables/PocoEntityArgumentBindingProviderTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Tables/TableArgumentBindingExtensionProviderTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Tables/TableEntityArgumentBindingProviderTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj
These changes allow users (or extension authors) to create their own custom Table bindings (e.g. a Table to IDictionary binding). This addresses the scenario discussed in #517. The way it works is, you author a ITableArgumentBindingExtensionProvider and register it with the JobHostConfiguration. We'll then pick up any extension bindings when binding functions.
```
JobHostConfiguration config = new JobHostConfiguration();
IExtensionRegistry extensions = config.GetService<IExtensionRegistry>();
extensions.RegisterExtension<ITableArgumentBindingExtensionProvider>(new MyTableArgumentBindingProvider());
```
> Adding extensibility for Table bindings 

- src/Microsoft.Azure.WebJobs.Host/Listeners/ListenerFactoryContext.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Bindings/MessageSenderExtensions.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Bindings/ServiceBusAttributeBindingProvider.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Bindings/ServiceBusBinding.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Bindings/ServiceBusEntity.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Bindings/StringToServiceBusEntityConverter.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Listeners/NamespaceManagerExtensions.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Listeners/ServiceBusQueueListenerFactory.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Listeners/ServiceBusSubscriptionListenerFactory.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/ServiceBusAttribute.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/ServiceBusTriggerAttribute.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Triggers/ServiceBusTriggerAttributeBindingProvider.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Triggers/ServiceBusTriggerBinding.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ServiceBusEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/Listeners/ServiceBusQueueListenerFactoryTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/Triggers/ServiceBusSubscriptionListenerFactoryTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/Triggers/ServiceBusTriggerBindingIntegrationTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/WebJobs.ServiceBus.UnitTests.csproj
This addresses scenarios where a client might only have Listen/Send rights to queues/topics, in which case the SDK should not attempt to "CreateIfNotExists" (which requires AccessRights.Manage). The default will remain Manage. This addresses issue #501.
The service bus Access levels/restrictions are documented here: https://msdn.microsoft.com/en-us/library/azure/dn205160.aspx
> Adding AccessRight declaration to ServiceBus binding Attributes

- src/Microsoft.Azure.WebJobs.Host/Config/ExtensionConfigContext.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/FunctionResult.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/JobHostContextFactory.cs
- src/Microsoft.Azure.WebJobs.Host/JobHostQueuesConfiguration.cs
- src/Microsoft.Azure.WebJobs.Protocols/SingletonParameterLog.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Config/ServiceBusConfiguration.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Config/ServiceBusExtensionConfig.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Listeners/DefaultMessageProcessorFactory.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Listeners/IMessageProcessorFactory.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Listeners/MessageProcessor.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Listeners/MessageProcessorFactoryContext.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Listeners/ServiceBusListener.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Listeners/ServiceBusQueueListenerFactory.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Listeners/ServiceBusSubscriptionListenerFactory.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Triggers/ServiceBusTriggerAttributeBindingProvider.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Triggers/ServiceBusTriggerBinding.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/WebJobs.ServiceBus.csproj
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ServiceBusEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/Config/ServiceBusExtensionConfigTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/Listeners/ServiceBusListenerTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/Listeners/ServiceBusQueueListenerFactoryTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/Triggers/ServiceBusSubscriptionListenerFactoryTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/Triggers/ServiceBusTriggerBindingIntegrationTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/WebJobs.ServiceBus.UnitTests.csproj
This PR addresses the issues discussed in #275. Specifically, it includes the following:
- new ServiceBusConfiguration.OnMessageOptions global default (for simplicity)
- Default OnMessageOptions now has concurrency set to 5 (was left at default 1 previously)
- added MessageProcessor which allows custom message processors to be used per queue/topic
- MessageProcessors are created by ServiceBusConfiguration.MessageProcessorFactory - the default   factory can be replaced to take control of creation, return custom processors, etc.
> Support for ServiceBus parallel execution + custom MessageProcessors

- src/Microsoft.Azure.WebJobs.Host/Bindings/Path/BindingTemplate.cs
- src/Microsoft.Azure.WebJobs.Host/Bindings/Path/BindingTemplateParser.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs
Moving the `rand-guid` support we added to Functions into the core SDK. This serves two goals:
1) Make it available to all users
2) Makes it a per-invocation resolution, so it works for early bound functions as well. In Functions currently, it only works for late bound functions (i.e. non-C#)
> Adding built-in rand-guid binding parameter support

- src/Microsoft.Azure.WebJobs.Host/Blobs/Listeners/ContainerScanInfo.cs
- src/Microsoft.Azure.WebJobs.Host/Blobs/Listeners/ScanBlobScanLogHybridPollingStrategy.cs
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/Blobs/Listeners/ScanBlobScanLogHybridPollingStrategyTests.cs
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/TestDoubles/FakeStorageBlobContainer.cs
Addresses #785.
It is possible for blob LastModified timestamps to be off by a few seconds when compared to the local machine. This would result in us missing new blobs after our initial scans. They'd later be picked up by the log-reading strategy, but that could be a delay of several minutes. This change reduces the chances of missing due to clock skew by basing our last scan-time on the latest-read blob, rather than on the local machine's time.
An example of where we could miss a blob before this change -- assume our local machine's clock is ahead of Azure by 2 seconds:
1. BlobA is added at 12:00:00. 
2. This is our first scan, so we pull it and see that it is new immediately after it has been added. We mark the 'last scan time' as 12:00:02 (because we're skewed ahead of Azure).
3. …
> addressing blob scan clock skew

- src/Microsoft.Azure.WebJobs.Host/Loggers/UpdateOutputLogCommand.cs
Fixes #675. 
`StringBuilder.ToString()` first allocates the string, then starts copying the buffered data to it until it reaches the end of its data. If you `Append()` more strings after the output string has been allocated, it will pass the end of the allocated string and you'll end up with the Exception we were seeing. 
By snapshotting the Length, we don't have that problem. Now the copying stops at the appropriate place, even if the `Append()` is called during `ToString()`. Thanks for brainstorming the solution @fabiocav!
> fixing threading bug in logging

- src/Microsoft.Azure.WebJobs.Host/Loggers/FunctionInstanceLogEntry.cs
- src/Microsoft.Azure.WebJobs.Logging/Entities/InstanceTableEntity.cs
- src/Microsoft.Azure.WebJobs.Logging/FunctionInstanceLogItem.cs
- test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/LoggerTest.cs
Fix https://github.com/Azure/azure-webjobs-sdk/issues/847
> Truncate log entries with silly  long string values.

- src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubAsyncCollector.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/EventHubAsyncCollectorTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/WebJobs.ServiceBus.UnitTests.csproj
EventHub can't send more than 256k of data at once. So the EventHub async collector needs to batch it. 
This is generally useful, so make the collector be public. 
Fix https://github.com/Azure/azure-webjobs-sdk/issues/834
Need to think of a good way to test this - none of the EventHub methods are virtual.
> MAke eventhub sending fit in 256k size limit

- src/Microsoft.Azure.WebJobs.Host/Indexers/DefaultBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/CollectorArgumentBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/PocoEntityWriter.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/TableAttributeBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/TypeUtility.cs
- src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj
- src/Microsoft.Azure.WebJobs/GlobalSuppressions.cs
- src/Microsoft.Azure.WebJobs/TableAttribute.cs
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/HostCallTests.cs
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/StorageTableExtensions.cs
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/TableTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Tables/PocoToTableEntityConverterTests.cs
Fix https://github.com/Azure/azure-webjobs-sdk-script/issues/753 
Add SDK Table bindings
[Table(name)] IAsyncCollector<JObject> 
[Table(name,pk,rk)] JObject 
[Table(name,pk?,filter?take?)] JArray
Previously, these cases where handled via binding code in Script. 
This leverages the new Binding factory rules (rather than the older class hierarchies).  I filed https://github.com/Azure/azure-webjobs-sdk/issues/887 to track switching Tables completely over, but that's too risky now and can be done later.  
I still need fixup script to take advantage of this and verify we can remove a bunch of the code in Script's TableBinding.  I may need to come back and change things in this PR from that.
> Table bindings for Script

- src/Microsoft.Azure.WebJobs.Host/Blobs/Triggers/BlobTriggerAttributeBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/DefaultStorageAccountProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/DefaultStorageCredentialsValidator.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/IStorageCredentialsValidator.cs
- src/Microsoft.Azure.WebJobs.Host/Queues/Bindings/QueueBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Queues/Triggers/QueueTriggerAttributeBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Singleton/SingletonManager.cs
- src/Microsoft.Azure.WebJobs.Host/Storage/IStorageAccount.cs
- src/Microsoft.Azure.WebJobs.Host/Storage/IStorageAccountExtensions.cs
- src/Microsoft.Azure.WebJobs.Host/Storage/StorageAccount.cs
- src/Microsoft.Azure.WebJobs.Host/Storage/StorageAccountType.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/TableAttributeBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/TestDoubles/FakeStorageAccount.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/DefaultStorageAccountProviderTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/DefaultStorageCredentialsValidatorTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Singleton/SingletonManagerTests.cs
related to #810 and [script/#773](https://github.com/Azure/azure-webjobs-sdk-script/issues/773)
Looking for initial feedback before I add tests & polish.
Added `StorageAccountType` to storage accounts, which is set to `premium` or `blobonly` in `validateCredentialsAsync`.  ~~In each binding provider I test if the storage account type is compatible with that attribute.~~
When you request a StorageAccount you supply the supported storage account types.  If the account is not of the supported type, we throw an error indicating the invalid type & what types are supported.
Added `SupportedTypes` to StorageAccountAttribute with default `All`, so that from functions we can disabled Premium storage for BlobTriggerAttributes.
``` c#
// to throw if 'somename' is a Premium storage account, you can …
```
> Validate storage account type against attribute bindings

- src/Microsoft.Azure.WebJobs.Host/Listeners/HostListenerFactory.cs
- src/Microsoft.Azure.WebJobs.Host/Loggers/TraceWriterFunctionInstanceLogger.cs
- src/Microsoft.Azure.WebJobs.Host/Singleton/SingletonListener.cs
- src/Microsoft.Azure.WebJobs.Host/Singleton/SingletonManager.cs
- src/Microsoft.Azure.WebJobs.Storage/StorageExceptionExtensions.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/BlobTriggerTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ServiceBusEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/JobHostTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/TraceWriterFunctionInstanceLoggerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Singleton/SingletonListenerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Singleton/SingletonManagerTests.cs
This removes our very verbose singleton logging (half of https://github.com/Azure/azure-webjobs-sdk-script/issues/728) and adds detailed debugging information should a renewal fail. Also adds function invocation ids to some of our other logging as it's currently tough to correlate events when looking through the logs.
> improving singleton logging

- WebJobs.proj
- WebJobs.sln
- appveyor.yml
- src/Microsoft.Azure.WebJobs.Host/JobHost.cs
- test/Dashboard.UnitTests/RestApiTests.cs
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/Queues/QueueTriggerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/ConverterManagerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/JobHostTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Singleton/SingletonValueProviderTests.cs
- tools/SkipStrongNames.xml
@mathewc @fabiocav 
After a bit of thinking, fudging with xunit or creating test only fixes aren't the way to go, we should prevent the deadlock itself, as with a funky setup a dev could run into this (+ it's cleaner).
Read this article, think it gives a good summary of options: https://blogs.msdn.microsoft.com/pfxteam/2012/04/13/should-i-expose-synchronous-wrappers-for-asynchronous-methods/
We could use `configureAwait(false)` all the way down, but that's a huge change and would break anyone calling sync methods from a sync context which requires posting back to the same thread.
`Task.Run(...)` in the publicly exposed Sync() methods executes the async call on a background thread, which keeps it from interacting with the caller's sync context (which is good, as if the caller is using a …
> Add appveyor test support

- src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubConfiguration.cs
We had these two values reversed. The guidance for these values is for the prefetch size to be 3 to 4 times larger than the max batch size.
PrefetchCount defaults to 300, so before these changes, we had MaxBatchSize=1000, PrefetchCount=300.
> Adjusting EventHub MaxBatchSize and PrefetchCount for performance

- src/Microsoft.Azure.WebJobs.ServiceBus/Triggers/BrokeredMessageToByteArrayConverter.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Triggers/BrokeredMessageToStringConverter.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/WebJobs.ServiceBus.csproj
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/BrokeredMessageToByteArrayConverterTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/BrokeredMessageToStringConverterTests.cs
Improving `BrokeredMessageToString` by not special-casing any `ContentType`s. We'll first try to read from the Stream and return that string. If that fails (because it was serialized differently), we'll then try the default serializer used by Service Bus. If that fails, we'll provide a slightly better error message than the default. Previously, sending a plain string with a null ContentType would fail as we'd attempt to deserialize it using the default serializer.
Improving `BrokeredMessageToByteArray` by throwing a slightly better error message if we're unable to deserialize. We can't implement the fallback here because deserializing a byte[] from a Stream will always work -- so we use the ContentTypes as a hint. The behavior here hasn't changed but I wrap the exception message (which …
> ServiceBus: improving BrokeredMessage string and byte[] conversions

- src/Microsoft.Azure.WebJobs.Host/Bindings/BindingDataProvider.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Bindings/BindingDataProviderTests.cs
This fix enables scenarios where the value provided is a type derived from the type used for binding. A concrete example is when binding to WebHooks (e.g. Slack) that read the payload as form data, which will result in a value of an internal ASP.NET type (`HttpValueCollection`), derived from NameValueCollection, which is the type intended to be used in user code.
> Fixing BindingDataProvider to enable binding to less derived types

- src/Microsoft.Azure.WebJobs.Host/Bindings/AttributeCloner.cs
- src/src.ruleset
- test/Microsoft.Azure.WebJobs.Host.UnitTests/AttributeClonerTests.cs
Make it less likely that users will accidentally cause their secret values to be written to error logs.
> Change AutoResolve error message

- src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexer.cs
- src/Microsoft.Azure.WebJobs.Host/TypeUtility.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/FunctionIndexerFactory.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Indexers/FunctionIndexerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/TypeUtilityTests.cs
Constantly in the forums and on StackOverflow users report issues with their job functions, and it often turns out to be that they have incorrectly defined an `async void` function. E.g. most recently on SO here: http://stackoverflow.com/questions/41876364/queue-messages-not-being-moved-to-the-poison-queue.
Since there are no good reasons to do this, any instances are most certainly a user error. So I'm throwing an indexing error in these cases.
> Emit a warning for async void functions

- src/Microsoft.Azure.WebJobs.Host/Tables/TableAttributeBindingProvider.cs
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/TableTests.cs
Hit by Script Powershell binding.
IAsyncCollector rule is allowed even if the attribute includes a Partition or RowKey. Powershell uses this for outputing a singleton.
> Fix a regression in table binding.

- CustomDictionary.xml
- src/Microsoft.Azure.WebJobs.Host/Bindings/AttributeCloner.cs
- src/Microsoft.Azure.WebJobs.Host/Bindings/BindingFactory.cs
- src/Microsoft.Azure.WebJobs.Host/Bindings/DefaultResolutionPolicy.cs
- src/Microsoft.Azure.WebJobs.Host/Bindings/FunctionBinding.cs
- src/Microsoft.Azure.WebJobs.Host/Bindings/IResolutionPolicy.cs
- src/Microsoft.Azure.WebJobs.Host/Bindings/ODataFilterResolutionPolicy.cs
- src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj
- src/Microsoft.Azure.WebJobs/AutoResolveAttribute.cs
- src/Microsoft.Azure.WebJobs/ODataFilterResolutionPolicy.cs
- src/Microsoft.Azure.WebJobs/TableAttribute.cs
- src/Microsoft.Azure.WebJobs/WebJobs.csproj
- test/Microsoft.Azure.WebJobs.Host.UnitTests/AttributeClonerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Common/CollectorTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/FakeQueue/FakeQueueAttribute.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/FakeQueue/FakeQueueClient.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs
I partially resurrected Mathew's PR here: https://github.com/Azure/azure-webjobs-sdk/pull/971. I'm going to need this to be able to move forward with DocDB so wanted to get an initial review out before writing lots of tests and plumbing i through everything.
One big change that @MikeStall will be interested in -- now passing the ValueBindingContext along with the resolved attribute to all of the builder methods (only ExactType is doing this for this initial PR).
> expanding ResolutionPolicy for public use

- src/Microsoft.Azure.WebJobs.Host/Bindings/PatternMatcher.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/ConverterManagerTests.cs
PatternMatcher would throw (from `specificType.GetGenericTypeDefinition`) if Type -> GenericType IConverter was defined when it should return false and move to evaluate the next IConverter.
Can occur if BindingRule IConverter and general IConverter are on the same class.
> Fix pattern matcher for BindingRules

- src/Microsoft.Azure.WebJobs.Host/Exceptions/FunctionException.cs
- src/Microsoft.Azure.WebJobs.Host/Exceptions/RecoverableException.cs
- src/Microsoft.Azure.WebJobs.Host/FunctionInvocationException.cs
- src/Microsoft.Azure.WebJobs.Host/FunctionTimeoutException.cs
- src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexer.cs
- src/Microsoft.Azure.WebJobs.Host/Triggers/FunctionTriggerException.cs
- src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Listeners/ListenerFactoryTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj
resolves #996 
Wrap function trigger listeners to catch errors and trace FunctionIndexingExceptions (which will be picked up by script). If handled, swallow, otherwise throw.
Also changed the `CreateTriggeredFunctionDefinition` method to be a bit less unwieldy (static -> instance and removed intermediate method to lessen parameter passing)
**REQUIRES CHANGES IN SCRIPT TO HANDLE NEW EXCEPTIONS**
> Propagate trigger listener exceptions

- src/Microsoft.Azure.WebJobs.Host/Listeners/FunctionListener.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Listeners/FunctionListenerTests.cs
So @MikeStall was right, we should have better handling for the stop case.
Propose that if we get a handled listener exception we attempt to stop the listener immediately.
> Disable listener stopasync if exception

- src/Microsoft.Azure.WebJobs.Host/Bindings/AttributeCloner.cs
- src/Microsoft.Azure.WebJobs.Host/ConfigurationUtility.cs
- test/Microsoft.Azure.WebJobs.Host.TestCommon/FakeNameResolver.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/AttributeClonerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/ConfigurationUtilityTests.cs
Fixed nameResolver.resolve(null) in `GetAppSettingResolver`
Also added null handling to ConfigurationUtility
> Fix null setting name bug

- src/Microsoft.Azure.WebJobs.Logging/Internal/LogWriter.cs
- src/Microsoft.Azure.WebJobs.Logging/LogFactory.cs
- test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/LoggerTest.cs
- test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/WebJobs.Logging.FunctionalTests.csproj
- test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/app.config
- test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/packages.config
This will enable better logging for https://github.com/Azure/azure-webjobs-sdk-script/issues/1245
In Functions, under load, you can get to a place where the logger is unable to write to Table storage because it is being throttled. Exceptions are thrown, but because they're coming from an unmonitored background Task, we never log them anywhere. This provides a callback so Exceptions can be logged.
There will be a corresponding change in Script that will log these to the TraceWriter. This will allow us to see how often this occurs. I'm not sure that there's a great solution to remove the issue completely (it would involve splitting the logs across more partitions) -- but the move to logging via Application Insights should make this less of an issue.
> Logging: add Exception callback for LogWriter

- src/Microsoft.Azure.WebJobs.Host/Bindings/AttributeCloner.cs
- src/Microsoft.Azure.WebJobs.Host/Bindings/DefaultAttributeInvokerDescriptor.cs
- src/Microsoft.Azure.WebJobs.Host/Bindings/FunctionBinding.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs
- src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexer.cs
- src/Microsoft.Azure.WebJobs.Host/Singleton/SingletonManager.cs
- src/Microsoft.Azure.WebJobs.Host/Triggers/TriggerArgumentBinding/SimpleTriggerArgumentBinding.cs
- src/Microsoft.Azure.WebJobs.Host/Triggers/TriggeredFunctionBinding.cs
- src/Microsoft.Azure.WebJobs.Protocols/FunctionDescriptor.cs
- src/Microsoft.Azure.WebJobs.Protocols/FunctionStartedMessageExtensions.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/FunctionExecutorTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Indexers/FunctionIndexerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Protocols/FunctionStartedMessageExtensionsTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Singleton/SingletonManagerTests.cs
related to #1060 
Ran some instrumentation on the webjobs sdk for the event hub perf stuff.
We spent ~25% of execution time in a few reflection related functions:
- invoke string
- singleton attributes
- timeout attribute
- trigger descriptor
- trigger argument binding
Moving all these operations to the indexing path.
I can post the before/after profiling data
> Move reflection off of execution path

- src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubConfiguration.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/EventHubTests.cs
This typo causes a stack overflow due to setter recursion.
I don't think we need to prioritize a release with the fix, only those using this setting & webjobs nightly builds could be impacted.
> Fix batchCheckpointFrequency setter

- src/Microsoft.Azure.WebJobs.Host/Executors/JobHostContext.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/JobHostContextTests.cs
Due to https://github.com/Azure/azure-webjobs-sdk-script/issues/1537, I'm temporarily removing the call to `Dispose()` as it can cause functions to error that haven't in the past. The real fix will be larger and take more time.
> temporarily removing LoggerFactory.Dispose()

- src/Microsoft.Azure.WebJobs.Host/Executors/JobHostContext.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/JobHostContextTests.cs
Fixes https://github.com/Azure/azure-webjobs-sdk-script/issues/1606
Note -- we can re-enable this b/c https://github.com/Azure/azure-webjobs-sdk-script/issues/1537 has been fixed.
> re-adding LoggerFactory disposal

- src/Microsoft.Azure.WebJobs.Host/Queues/Listeners/QueueListener.cs
- src/Microsoft.Azure.WebJobs.Host/Queues/QueueProcessor.cs
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/Queues/QueueListenerTests.cs
Reducing the number of places that we do our property updates to get 8.x working. I missed a scenario where we do a background message update, which changes the pop receipt. That caused future deletes to break.
Instead, taking @mathewc's advice and reducing the number of places we replace -- ensuring that the common scenario of poison-queue-handling works in 8.x as expected. If you are adding existing messages to queues from within your function in 8.x, we'll no longer be able to successfully delete that message, but that is manageable for the end-user.
> fixing queue visibility renewals

- src/Microsoft.Azure.WebJobs.Host/Executors/DefaultStorageAccountProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/DefaultStorageCredentialsValidator.cs
- src/Microsoft.Azure.WebJobs.Host/Queues/Bindings/QueueBindingProvider.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/DefaultStorageAccountProviderTests.cs
Improvement for connection exhaustion.
For non storage/dashboard accounts, we were running the validation calls (blob endpoint & queue endpoint http calls) every time we called `TryGetAccountAsync`
> Storage account caching and validation fix

- src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/Aggregator/FunctionResultAggregatorConfiguration.cs
Improves the scenario from https://github.com/Azure/azure-webjobs-sdk/issues/1126
> improving Exception messages for BatchSize and FlushTimeout

- src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs
- src/Microsoft.Azure.WebJobs.Host/Loggers/FunctionInstanceLogEntry.cs
- src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/Aggregator/FunctionResultAggregator.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/ILoggerTests.cs
- test/Microsoft.Azure.WebJobs.Host.TestCommon/TestHelpers.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/JobHostConfigurationTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/FunctionExecutorLogOrdering.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj
Add an aggressive unit test to verify ordering, including in failure situations.
This is SDK support for Script bug (https://github.com/Azure/azure-webjobs-sdk-script/issues/578 , PR  https://github.com/Azure/azure-webjobs-sdk-script/pull/1660 ) , which will consume the event.
> Add a pre-bind logging instrumentation end point.

- src/Microsoft.Azure.WebJobs.Host/Bindings/FunctionBinding.cs
- src/Microsoft.Azure.WebJobs.Host/Bindings/FunctionBindingContext.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs
- src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexer.cs
- src/Microsoft.Azure.WebJobs.Host/Listeners/HostListenerFactory.cs
- src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/LoggerExtensions.cs
- src/Microsoft.Azure.WebJobs.Host/Singleton/SingletonListener.cs
- src/Microsoft.Azure.WebJobs.Host/Singleton/SingletonManager.cs
- src/Microsoft.Azure.WebJobs.Host/Singleton/SingletonValueProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Triggers/TriggeredFunctionBinding.cs
- src/Microsoft.Azure.WebJobs.Protocols/FunctionDescriptor.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/FunctionExecutorTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Listeners/HostListenerFactoryTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Singleton/SingletonListenerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Singleton/SingletonManagerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Singleton/SingletonValueProviderTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj
Fully rely on FunctionDescriptor.
Remove FunctionDescriptor.MethodInfo. Adding new fields on FunctionDescriptor like LogName, IsDisabled, HasCanncelationtoken.
methodInfo.DeclaringType.Name + "." +methodInfo.Name --> FunctionDescriptor.ShortName
methodInfo.Name --> FunctionDescriptor.LogName
Continuation of work started in
https://github.com/Azure/azure-webjobs-sdk/commit/183e3c4f194c7a670dd11465ec0e92014ad8dd46
No functional change here. This is prepping for the [FunctionName] support. (https://github.com/Azure/azure-webjobs-sdk/issues/1170)
> Remove usage of MethodInfo throughout code. 

- src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs
AppInsight was using fast logger structures without subscribing to a fast logger.
> Fix log ordering bug.

- src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/FunctionInstanceFactoryContext.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/FunctionInvoker.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/FunctionInvokerFactory.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/IFunctionInvoker.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/IMethodInvoker.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/JobHostConfigurationExtensions.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/MethodInvokerFactory.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/MethodInvokerWithReturnValue.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/TaskMethodInvoker.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/TriggeredFunctionExecutor.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/VoidTaskMethodInvoker.cs
- src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexer.cs
- src/Microsoft.Azure.WebJobs.Host/Triggers/TriggerData.cs
- src/Microsoft.Azure.WebJobs.Host/Triggers/TriggeredFunctionBinding.cs
- src/Microsoft.Azure.WebJobs.Host/Triggers/TriggeredFunctionInstanceFactory.cs
- src/Microsoft.Azure.WebJobs.Host/TypeUtility.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/FunctionExecutorTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/FunctionInvokerFactoryTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/FunctionInvokerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/MethodInvokerFactoryTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/TaskMethodInvokerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/TriggeredFunctionExecutorTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/VoidMethodInvokerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Indexers/FunctionIndexerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Indexers/ReturnValueTests.cs
This is to resolve https://github.com/Azure/azure-webjobs-sdk/issues/1104.
Phase 1 simply allows functions in WebJobs to have a return value. Previously we supported `void` and `Task`. With this change, we also support `TReturnValue` and `Task<TReturnValue>`.
Example functions I'm using for testing:
```csharp
public static int QueueTriggerWithReturnValue(
[QueueTrigger("test")] string message)
{
Console.WriteLine("Processed message: " + message);
return 5;
}
public static Task<int> QueueTriggerWithReturnValueAsync(
[QueueTrigger("test")] string message)
{
Console.WriteLine("Processed message: " + message);
return Task.FromResult(5);
}
```
Phase 2 (TBD) is to connect the return value back to the trigger binding.
> Return value support for BYOB

- src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndex.cs
- src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexer.cs
- src/Microsoft.Azure.WebJobs.Host/Indexers/IFunctionIndexLookup.cs
- src/Microsoft.Azure.WebJobs.Host/JobHost.cs
- src/Microsoft.Azure.WebJobs.Protocols/FunctionDescriptor.cs
- src/Microsoft.Azure.WebJobs/FunctionNameAttribute.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Common/BindToGenericItemTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/EmptyFunctionIndexProvider.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Indexers/FunctionNameTests.cs
SDK honors [FunctionName] attribute
Resolve https://github.com/Azure/azure-webjobs-sdk/issues/1170
ADd new JobHost.CallAsync(string) endpoint which can honor the method name.
> SDK honors [FunctionName] attribute

- src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/FunctionInstanceFactoryContext.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/FunctionInvoker.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/FunctionInvokerFactory.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/IFunctionInvoker.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/IMethodInvoker.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/JobHostConfigurationExtensions.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/MethodInvokerFactory.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/MethodInvokerWithReturnValue.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/TaskMethodInvoker.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/TriggeredFunctionExecutor.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/VoidTaskMethodInvoker.cs
- src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexer.cs
- src/Microsoft.Azure.WebJobs.Host/Triggers/TriggerData.cs
- src/Microsoft.Azure.WebJobs.Host/Triggers/TriggeredFunctionBinding.cs
- src/Microsoft.Azure.WebJobs.Host/Triggers/TriggeredFunctionInstanceFactory.cs
- src/Microsoft.Azure.WebJobs.Host/TypeUtility.cs
- src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/FunctionExecutorTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/FunctionInvokerFactoryTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/FunctionInvokerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/MethodInvokerFactoryTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/TaskMethodInvokerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/TriggeredFunctionExecutorTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/VoidMethodInvokerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Indexers/FunctionIndexerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Indexers/ReturnValueTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj
This takes the BYOB return value changes from the dev branch and brings them to v2.x.
There are some minor changes that were made in addition to the cherry-pick due to bugs that were found during integration testing with Durable Functions (this testing was not possible in the dev branch since DF does not yet support .NET Core).  A minor change will need to be made back in the dev branch for v3.x as a separate PR to make the two branches functionally equivalent.
> Return value support for BYOB (v2.x)

- src/Microsoft.Azure.WebJobs.Host/Executors/JobHostContext.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/JobHostContextTests.cs
Temporarily addresses https://github.com/Azure/azure-webjobs-sdk-script/issues/1690
> removing LoggerFactory disposal again

- src/Microsoft.Azure.WebJobs.Host/Queues/Listeners/QueueListener.cs
- src/Microsoft.Azure.WebJobs.Host/Timers/TaskSeriesTimer.cs
- src/Microsoft.Azure.WebJobs.Storage/StorageExceptionExtensions.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsightsEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.TestCommon/TestExceptionHandler.cs
We had a series of E2E tests failing due to unhandled `StorageException`s. It looks like the Core version of the Storage SDK is inconsistent with what exception it handles during task cancellation. This affects us during shutdown, which is where these exceptions were coming from. I've filed https://github.com/Azure/azure-storage-net/issues/512 to track in the storage SDK.
For now, we'll handle both wherever we need to.
I also changed the TestExceptionHandler to fail a test if it gets an unexpected exception. This will let us know if there are other unhandled issues that we're missing.
> workaround for TaskCanceledExceptions wrapped in StorageException

- src/Microsoft.Azure.WebJobs.Host/AssemblyNameCache.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/JobHostConfigurationExtensions.cs
- src/Microsoft.Azure.WebJobs.Host/Extensions/JobHostMetadataProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Indexers/DefaultTypeLocator.cs
- src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj
- test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs
These are changes proposed by Kranthi based on results from his performance tests.
The `Assembly.GetName()` calls throughout the code are fairly expensive, and caching the result has a measurable impact.
> Caching assembly name resolution

- src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/FunctionInvoker.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/IFunctionInvoker.cs
- src/Microsoft.Azure.WebJobs.Host/Triggers/TriggeredFunctionInstanceFactory.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/FunctionExecutorTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/FunctionInvokerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/TriggeredFunctionExecutorTests.cs
IFunctionInvoker needs to take in the job instance separately from InvokeAsync() so we can use it in filters.
> Port change from dev

- src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs
- src/Microsoft.Azure.WebJobs.Host/Loggers/FunctionInstanceLogEntry.cs
- src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/Aggregator/FunctionResultAggregate.cs
- src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/Constants/LogConstants.cs
- src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/Constants/ScopeKeys.cs
- src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/LoggerExtensions.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsScope.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/FilteringTelemetryProcessor.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobsTelemetryInitializer.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsightsEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/FilteringTelemetryProcessorTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/FunctionResultAggregatorTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/LoggerExtensionsTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs
This is the `dev` version of #1265.
Also pulling in the change @MikeStall made to fix logger scope (#1248). That change only went into `v2.x`.
> [AppInsights] using start/stop on RequestTelemetry to support Profiler

- src/Microsoft.Azure.WebJobs.Host/Bindings/Cancellation/CancellationTokenBinding.cs
Fix being unable to call an instance of the `JobHost `with a custom `CancellationToken`.
```
CancellationToken customCancellationToken = cancellationTokenSource.Token;
_jobHost.Call(testFunction, new {customCancellationToken});
```
This currently gives an `Unable to convert value to CancellationToken.` error.
> Fix unable to bind custom CancellationTokens

- src/Dashboard/Dashboard.csproj
- src/Dashboard/Web.config
- src/Dashboard/packages.config
- src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj
- src/Microsoft.Azure.WebJobs.Host/packages.config
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobs.Logging.ApplicationInsights.csproj
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/packages.config
- src/Microsoft.Azure.WebJobs.ServiceBus/WebJobs.ServiceBus.csproj
- src/Microsoft.Azure.WebJobs.ServiceBus/packages.config
- src/Microsoft.Azure.WebJobs/WebJobs.csproj
- src/Microsoft.Azure.WebJobs/packages.config
There was some C# 7 syntax that we weren't able to use b/c StyleCop didn't like it. The new version came out recently and appears to fix those issues.
Edit: @mamaso reminded me that we actually can't use C# 7 in this repo due to the build server. However, we should still move StyleCop forward so I changed this to *also* restrict our build to C# 6 syntax. Once that restriction is lifted, we'll be all set with new StyleCop too.
Edit 2: Now that the C# 6 restriction is lifted in the internal build, I've also removed it here. So now this is **only a StyleCop update**
> updating StyleCop to v5.0.0

- src/Microsoft.Azure.WebJobs.Host/AmbientConnectionStringProvider.cs
- src/Microsoft.Azure.WebJobs.Host/ConfigurationUtility.cs
- src/Microsoft.Azure.WebJobs.Host/DefaultNameResolver.cs
- src/Microsoft.Azure.WebJobs.Host/JobHostConfiguration.cs
- src/Microsoft.Azure.WebJobs.Host/Listeners/HostListenerFactory.cs
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/StorageAccountTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/ConfigurationUtilityTests.cs
This is a small change to better enable the CLI (and other clients) to more cleanly pass configuration settings.
> Exposing basic configuration extensibility

- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs
> [AppInsights] changing to use requestTelemetry.Start()

- WebJobs.sln
- appveyor.yml
- src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubAsyncCollector.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubConfiguration.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubListener.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubTriggerAttributeBindingProvider.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubTriggerInput.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubTriggerInputBindingStrategy.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/Properties/AssemblyInfo.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/SystemPropertiesCollectionExtensions.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/WebJobs.EventHubs.csproj
- test/Microsoft.Azure.WebJobs.EventHubs.UnitTests/WebJobs.EventHubs.UnitTests.csproj
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AzureStorageEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/EventHubEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/WebJobs.Host.EndToEndTests.csproj
- test/Microsoft.Azure.WebJobs.Host.TestCommon/TestHelpers.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/EventHubAsyncCollectorTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/EventHubTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/Listeners/EventHubListenerTests.cs
@MikeStall made the convincing argument for backporting changes
related https://github.com/Azure/azure-webjobs-sdk-extensions/pull/267
> Migrate event hubs to dotnet core

- src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/Aggregator/FunctionResultAggregate.cs
- src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/Aggregator/FunctionResultAggregator.cs
- src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/Constants/LogConstants.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLoggerProvider.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/DefaultTelemetryClientFactory.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/FilteringTelemetryProcessor.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobsTelemetryInitializer.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/LoggerExtensionsTests.cs
Fixes #1323.  
App Insights has support for Max/Min/Sum on each of their metrics. Previously we were sending MaxDuration/MinDuration/AvgDuration as individual metrics. This change now sends a single Duration metric with Count/Min/Max/Sum all populated.
> [AppInsights] reducing metrics from Aggregator

- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs
The tests all failed until I added the `HttpRequest` key to the exclusion list. I'm also prepping a private site extension to verify it works.
> [AppInsights] removing some HTTP details from telemetry

- src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/LoggerExtensions.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsightsEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/LoggerExtensionsTests.cs
Fixes #1352 by removing all parameter logs. In order to log parameter details, a Function can do it from a Trace.
> [AppInsights] Remove parameter logging for RequestTelemetry

- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs
Fixes #1365.
The issue here is that the `ExceptionTelemetry.Message` property didn't behave as I expected. It overwrites the exception message of the most outer exception in the payload that gets sent to App Insights. If you had nested exceptions, the inner (most important) ones would still look correct, which is why our normal exception throwing still contains the relevant details.
This change moves any supplied log message to a `FormattedMessage` property, which will show up in `customDimensions` in Analytics. This way you can still add additional logging details to supplement the exception itself.
I've added tests that use reflection to double-check that we're not mangling the internal data. These both failed before the change and pass after.
This will also be ported to `dev`.
> [AppInsights] improving Exception logging

- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/DefaultTelemetryClientFactory.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobs.Logging.ApplicationInsights.csproj
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobsRoleEnvironmentTelmetryInitializer.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/DefaultTelemetryClientFactoryTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/WebJobsRoleEnvironmentTelemetryInitializerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj
Fixes #1366.
Due to #1369, we cannot rely on WEBSITE_HOSTNAME for slots, which is what the `AzureWebAppRoleEnvironmentTelemetryInitializer`. So I took that class and changed it to calculate the name with stable environment variables.
I'm about to start testing this with a private site extension but wanted to get the PR out.
I'll move this to `dev` immediately after this is in for `v2.x`.
> [AppInsights] changing RoleName calculation to work with Functions slots

- tools/PollSigningResults.ps1
Builds have been failing due to not waiting long enough for signing to complete. This should resolve.
> Increase signing poll time to 5 minutes

- src/Microsoft.Azure.WebJobs.Host/ConfigurationUtility.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/ConfigurationUtilityTests.cs
Resolves #1408 
This is a temporary fix as the `ConfigurationUtility` type will be removed as part of the DI work, but the default behavior introduced with this change will be maintained.
> Changing configuration setup order so environment variables take precendence over app settings

- src/Microsoft.Azure.WebJobs.Host/Config/ExtensionConfigContext.cs
- src/Microsoft.Azure.WebJobs/BindingAttribute.cs
* HandlesReturnValue attribute is intended for use by extension trigger bindings to indicate to non-C# languages that a return value should be expected.
> [WIP] Added HandlesReturnValue attribute.

- src/Microsoft.Azure.WebJobs.Host/GlobalSuppressions.cs
- src/Microsoft.Azure.WebJobs.Host/JobHost.cs
Adding protected virtuals to allow host subclasses to implement custom logic at certain stages of host startup. The problem is that currently initialization, indexing and listener startup are all baked into RunAndBlock. In some scenarios (e.g. Azure Functions - see PR https://github.com/Azure/azure-webjobs-sdk-script/pull/2147) subclasses need to implement custom state transition logic at the right points. These changes enable this.
> Adding protected host state transition methods

- src/Microsoft.Azure.WebJobs.Host/Bindings/DefaultAttributeInvokerDescriptor.cs
- src/Microsoft.Azure.WebJobs.Host/Config/ExtensionConfigContextExtensions.cs
- src/Microsoft.Azure.WebJobs/AppSettingAttribute.cs
- src/Microsoft.Azure.WebJobs/AutoResolveAttribute.cs
- src/Microsoft.Azure.WebJobs/IAttributeInvokeDescriptor.cs
Anything used to decorate a binding attribute goes into the Microsoft.Azure.WebJobs.Description namespace.
Notably [AppSetting] and [AutoResolve]
Remove more [Obsolete] attributes.
> Namespace updates, remove [Obsolete]s

- src/Microsoft.Azure.WebJobs.Host/Dispatch/InMemoryDispatchQueueHandler.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/DispatchQueueEndToEndTests.cs
most of the logic is in `src/Microsoft.Azure.WebJobs.Host/Queues/SharedQueueHandler.cs`
the idea is to have a workload queue per host so that a single http request with a batch payload can be processed by multiple instances (in the case of [EventGrid](https://github.com/Azure/azure-functions-eventgrid-extension))
In order to use it, user needs to implement a `messageHandler`:
```
public abstract class MessageHandler
{
/// <summary>
/// Default implementation returns null
/// </summary>
public virtual CloudQueue PoisonQueue => null;
/// <summary>
/// from JObject to actual function execution
/// if generic is used, object serialization error might happen at runtime
/// </summary>
public abstract Task<FunctionResult> TryExecuteAsync(JObject data, CancellationToken cancellationToken);
``` …
> Add a sharedQ for distribute the workload

- src/Microsoft.Azure.WebJobs.Host/Executors/JobHostConfigurationExtensions.cs
- src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexer.cs
- src/Microsoft.Azure.WebJobs.Host/JobHostConfiguration.cs
- src/Microsoft.Azure.WebJobs.Host/JobHostFunctionTimeoutConfiguration.cs
- src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj
- test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs
Fix https://github.com/Azure/azure-webjobs-sdk-script/issues/2105
Still need an update in Script to set this.
> Allow specifying a timeout at the JobHostConfiguration level.

- src/Microsoft.Azure.WebJobs.Host/ConnectionStringNames.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/DefaultStorageAccountProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/JobHostConfigurationExtensions.cs
- src/Microsoft.Azure.WebJobs.Host/JobHostConfiguration.cs
- src/Microsoft.Azure.WebJobs.Host/JobHostInternalStorageConfiguration.cs
- src/Microsoft.Azure.WebJobs.Host/Singleton/BlobLeaseDistributedLockManager.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/InternalStorageTests.cs
- test/Microsoft.Azure.WebJobs.Host.TestCommon/EnvVarHolder.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/JobHostConfigurationTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Singleton/SingletonManagerTests.cs
Allow when we have no full Connection strings involved, just a SAS URL to storage container. Added a new property on JobHostConfiguration to describe the sas. 
Config looks like:
config.HostId = "hostid1234";
config.StorageConnectionString = null;
config.DashboardConnectionString = null;
**config.SaSContainerConnectionString= "xxxx my container SAS xxxx"**
> Allow SDK to run purely off just a SAS connection string to a container

- src/Microsoft.Azure.WebJobs.Host/Executors/JobHostConfigurationExtensions.cs
- src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexer.cs
- src/Microsoft.Azure.WebJobs.Host/JobHostConfiguration.cs
- src/Microsoft.Azure.WebJobs.Host/JobHostFunctionTimeoutConfiguration.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs
https://github.com/Azure/azure-webjobs-sdk/pull/1464 from Functions v1 (sdk v2) branch
Allow specifying a timeout at the JobHostConfiguration level rather than only via per-function Timeout attributes.
Fix https://github.com/Azure/azure-webjobs-sdk-script/issues/2105
> Port timeout fix

- src/Microsoft.Azure.WebJobs.ServiceBus/Config/ServiceBusExtensionConfig.cs
System.Private.CoreLib: No parameterless constructor defined for this object.
https://github.com/Azure/azure-webjobs-sdk/issues/1329#issuecomment-355330725
> Fix ServiceBus extension initialization

- src/Microsoft.Azure.WebJobs.Host/Tables/TableEntityWriter.cs
- src/Microsoft.Azure.WebJobs.Storage/StorageExceptionExtensions.cs
Adding extension method for getting and showing extra data on StorageException's from failed batch operations. This is a workaround to patch the unspecific error message 'Element {i} in the batch returned an unexpected response code'.
Resolves #1300
> Add error details on Azure Storage batched operation failures (v1)

- src/Microsoft.Azure.WebJobs.Host/Tables/TableEntityWriter.cs
- src/Microsoft.Azure.WebJobs.Storage/StorageExceptionExtensions.cs
Adding extension method for getting and showing extra data on StorageException's from failed batch operations. This is a workaround to patch the unspecific error message 'Element {i} in the batch returned an unexpected response code'.
Resolves #1300
(v1 version of the PR: https://github.com/Azure/azure-webjobs-sdk/pull/1480)
Tested manually locally, tested v1 change in prod too
> Add error details on Azure Storage batched operation failures (v2)

- src/Microsoft.Azure.WebJobs.Host/Singleton/BlobLeaseDistributedLockManager.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Singleton/SingletonManagerTests.cs
We found this issue while trying to repro another issue. Turns out we weren't using the proposedLeaseId when we first create a blob for locking. Pretty simple fix; added a regression test that failed before the fix was applied.
> fixing a missing proposed lease id in BlobLeaseDistributedLockManager

- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLoggerExtensions.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/DefaultTelemetryClientFactory.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobs.Logging.ApplicationInsights.csproj
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsightsEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/WebJobs.Host.EndToEndTests.csproj
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/WebJobs.Host.FunctionalTests.csproj
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/DefaultTelemetryClientFactoryTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/FilteringTelemetryProcessorTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj
- test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/WebJobs.Logging.FunctionalTests.csproj
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/WebJobs.ServiceBus.UnitTests.csproj
Fixes #1419 
Note that perf counters still are not enabled because they are missing from the App Insights .NET Core SDK. The Live Metrics view explains this so hopefully we don't get any issues raised on us directly:
> moving App Insights to 2.5; re-adding QuickPulse and Sampling

- .gitignore
- WebJobs-WithAnalyzers.sln
- appveyor.yml
- build.sh
Removing analyzers from the default solution. 
The analyzer projects were in the old project format, introducing some build issues and additional dependencies. #1554 tracks some work that needs to be done to fix the current analyzer project structure.
> Removing analyzers from WebJobs solution and introducing a solution with them

- src/Microsoft.Azure.WebJobs.Host/JobHostQueuesConfiguration.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/JobHostQueuesConfigurationTests.cs
Fix for https://github.com/Azure/azure-webjobs-sdk/issues/1568
This has come up many times as a usability issue when trying to explain to people how to enforce singleton processing. I always say set BatchSize=1 and NewBatchThreshold=0 but that isn't allowed currently.
> Allow NewBatchThreshold to be set to 0 (#1568)

- src/Microsoft.Azure.WebJobs.Host/AzureStorageDeploymentValidator.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs
Fixes #1574.
Storage SDK version 9.0.0 removed `TableServiceContext`, which means this check fails at runtime. I changed the check to be reflection- and version-based to make sure that we continue to enforce the check on versions where it is required (those under 8,0.0). 
I ran all the tests on both version 7.2.1 and 9.0.0 and they all passed. I manually verified that removing one of the assemblies (Microsoft.Data.Services.Client, Microsoft.Data.OData, Microsoft.Data.Edm) continued to fail this check in 7.2.1.
> changing AzureStorageDeploymentValidator to work with Storage SDK 9.0

- src/Microsoft.Azure.WebJobs.Host/Queues/Bindings/QueueBindingProvider.cs
SetPostResolveHook and BindToOutput builder logic duplicated. A clear bug that may be the cause of #1467, but still needs to be investigated.
> Queue Binding Bug

- src/Microsoft.Azure.WebJobs.ServiceBus/MessagingProvider.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/MessagingProviderTests.cs
Changes to "missing connection string" error message to distinguish between missing custom-defined connection string vs. missing unnamed (default) connection string.
Resolves #1524
> Update ServiceBusTrigger Error Message V1 (always appends "AzureWebJobs" to connection string name)

- src/Microsoft.Azure.WebJobs.ServiceBus/ServiceBusAccount.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/ServiceBusAccountTests.cs
Changes to "missing connection string" error message to distinguish between missing custom-defined connection string vs. missing unnamed (default) connection string.
Resolves #1524
> Update ServiceBusTrigger Error Message V2 (always appends "AzureWebJobs" to connection string name)

- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobs.Logging.ApplicationInsights.csproj
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/WebJobs.Host.EndToEndTests.csproj
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/WebJobs.Host.FunctionalTests.csproj
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj
- test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/WebJobs.Logging.FunctionalTests.csproj
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/WebJobs.ServiceBus.UnitTests.csproj
Removing this as the HTTP pipeline is different in v2 and this logging wasn't working as intended. Filed issue https://github.com/Azure/azure-functions-host/issues/2447 with details.
> removing App Insights HTTP result handling; updating to App Insights 2.5 RTM

- src/Microsoft.Azure.WebJobs.ServiceBus/MessageProcessor.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/MessageProcessorTests.cs
Fix for https://github.com/Azure/azure-webjobs-sdk/issues/1605
As you can see from the ServiceBus [message pump source code](https://github.com/Azure/azure-service-bus-dotnet/blob/90ce19dd89cad09065103ed7bb7994e73c6cc8bb/src/Microsoft.Azure.ServiceBus/MessageReceivePump.cs#L143) the contract when using the MessageReceiver.OnMessageAsync callback pattern is that SB handles the message state for you based on whether your callback throws an exception or not.
Here's what was happening:
- user function throws an exception
- our MessageProcessor calls `BrokeredMessage.AbandonAsync()` but **does not propagate exception**
- SB interprets lack of exception as success and internally calls `BrokeredMessage.CompleteAsync()`, completing an already abandoned message
- from my testing this causes all …
> ServiceBus MessageProcessor fix (#1605)

- WebJobs.proj
- appveyor.yml
- src/Common/CommonAssemblyInfo.cs
- src/Dashboard/Properties/AssemblyInfo.cs
- src/Microsoft.Azure.WebJobs.Host/Properties/AssemblyInfo.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Properties/AssemblyInfo.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobs.Logging.ApplicationInsights.csproj
- src/Microsoft.Azure.WebJobs.Logging/Properties/AssemblyInfo.cs
- src/Microsoft.Azure.WebJobs.Logging/WebJobs.Logging.csproj
- src/Microsoft.Azure.WebJobs.Protocols/Properties/AssemblyInfo.cs
- src/Microsoft.Azure.WebJobs.Protocols/WebJobs.Protocols.csproj
- src/Microsoft.Azure.WebJobs.ServiceBus/Properties/AssemblyInfo.cs
- src/Microsoft.Azure.WebJobs.Storage/Properties/AssemblyInfo.cs
- src/Microsoft.Azure.WebJobs.Storage/WebJobs.Storage.csproj
- src/Microsoft.Azure.WebJobs/Properties/AssemblyInfo.cs
- src/Microsoft.Azure.WebJobs/WebJobs.csproj
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs
- tools/NuGetProj.settings.targets
Improving some build processes:
- all projects now use `CommonAssemblyInfo.cs`
- inject the build number into `AssemblyFileVersion`
- inject the build number and commit SHA into `AssemblyInformationalVersion`
- remove need for `IncludeBuildNumberInVersion` environment variable. Now we'll append the build number *unless* the commit we're building has a tag. Then we assume it's official and leave it off.
> build improvements

- src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubListener.cs
Resolves #1626 
The same cancellation token should be passed through to user code in both the single dispatch and multi dispatch case.
I briefly looked at creating a unit test for this but its pretty painful due to the coupling with the Event Hubs types that aren't really mockable.
I'll send a matching PR for V2.
> Event Hubs cancellation token fix for batched mode

- src/Microsoft.Azure.WebJobs.Host/Extensions/JobHostMetadataProvider.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/JobHostMetadataProviderTests.cs
ServiceBus doesn't use the new binding rules (yet), so we're just registering the older-style `IBindingProvider`.  When script attempts to bind to this, it first consults the `IBindingRuleProvider`s to find the default type. Because there are none, it doesn't find any default type to use.
For input bindings, we already choose to try `string` in this case, but for outputs, we threw an exception. This sets `IAsyncCollector<string>` as the default fallback for output bindings.
@MikeStall -- I'm guessing the real fix is to completely deprecate `IBindingProvider` require everything to use rules?
> defining a default output binding type

- src/Microsoft.Azure.WebJobs.Host/Executors/DefaultStorageAccountProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Queues/Bindings/QueueBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/TableExtension.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncCancellationEndToEndTests.cs
Dupe of PR #1631, which had strange merge behavior
In the binding flow, there is a point where we transition from async code => sync code => async code. In the sync => async transition, we force the async code to run synchronously by using Task.Run(() => AsyncMethod().GetAwaiter().GetResult() on the async method.
This pattern leads to thread pool contention.
Task.Run() creates a child thread, AsyncMethod() does the work that the parent thread needs, and GetAwaiter().GetResult() blocks the parent thread until the work from AsyncMethod() is completed. In low throughput scenarios, this pattern doesn't cause visible issues because there are enough threads in the thread pool to complete the work in AsyncMethod(). However, when there is a high volume of requests through this code path that …
> Perf improvement on queue/table bindings in high throughput scenarios (V1)

- src/Microsoft.Azure.WebJobs.Host/Executors/DefaultStorageAccountProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Queues/Bindings/QueueBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Tables/TableExtension.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncCancellationEndToEndTests.cs
V2 version of #1657
In the binding flow, there is a point where we transition from async code => sync code => async code. In the sync => async transition, we force the async code to run synchronously by using Task.Run(() => AsyncMethod().GetAwaiter().GetResult() on the async method.
This pattern leads to thread pool contention.
Task.Run() creates a child thread, AsyncMethod() does the work that the parent thread needs, and GetAwaiter().GetResult() blocks the parent thread until the work from AsyncMethod() is completed. In low throughput scenarios, this pattern doesn't cause visible issues because there are enough threads in the thread pool to complete the work in AsyncMethod(). However, when there is a high volume of requests through this code path that blocks on GetAwaiter().GetResult(), …
> Perf improvement on queue/table bindings in high throughput scenarios (V2)

- src/Microsoft.Azure.WebJobs.Extensions.EventHubs/EventHubJobHostConfigurationExtensions.cs
All the other extensions have an overload NOT taking the config object if defaults are to be used.
> Adding overload for UseEventHub extension method

- src/Microsoft.Azure.WebJobs.Host/Listeners/FunctionListener.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Listeners/FunctionListenerTests.cs
Fix for https://github.com/Azure/azure-webjobs-sdk/issues/1691.
> Fixing listener retry race condition (#1691)

- src/Microsoft.Azure.WebJobs.Host/ConfigurationUtility.cs
- src/Microsoft.Azure.WebJobs.Host/WebJobsEnvironmentVariablesConfigurationSource.cs
- test/Microsoft.Azure.WebJobs.Host.TestCommon/EnvVarHolder.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/ConfigurationUtilityTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/DefaultStorageAccountProviderTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Listeners/HostListenerFactoryTests.cs
Addresses https://github.com/Azure/azure-webjobs-sdk/issues/1689
Applying same fix that we did for Azure Functions in https://github.com/Azure/azure-functions-host/commit/29397abfc80b2850164cf2c3da4ec380f4ede607. There are Azure Functions tests/scenarios currently disabled due to this bug (e.g. [this test](https://github.com/Azure/azure-functions-host/blob/ef311c8c4a46e6494e0b6b4af359586bb1295667/test/WebJobs.Script.Tests/Binding/CoreExtensionsScriptBindingProviderTests.cs#L17)).
Eventually just like in Functions the static config that ConfigurationUtility is doing will go away - this is a stepping stone to get things working consistently up and down the stack.
> Fixing IConfiguration environment variable caching

- src/Microsoft.Azure.WebJobs.Host/Indexers/DefaultTypeLocator.cs
Resolves #1722
This improves the experience and allows proper identification of the root cause of issues #1681 #1715 and the issues listed in #1722
```
Warning: Only got partial types from assembly: ClassLibrary1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Exception message: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
at System.Reflection.Assembly.GetTypes()
at Microsoft.Azure.WebJobs.Host.Indexers.DefaultTypeLocator.FindTypes(Assembly assembly, IEnumerable`1 extensionAssemblies) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\DefaultTypeLocator.cs:line 120
```
``` …
```
> Logging loader exception details when calls to GetTypes in DefaultTypeLocator throws a ReflectionTypeLoadException

- src/Microsoft.Azure.WebJobs.Host/Indexers/ExtensionTypeLocator.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AzureStorageEndToEndTests.cs
Changes to ExtensionTypeProvider to avoid the use of the DefaultTypeProvider. Removal of the code path that loads ICloudBlobStreamBinder<T> implementations.
**THIS IS A TACTICAL CHANGE**. Proper fix should come after the hosting/DI changes land, and would be the removal of all deprecated interfaces (e.g. `IExtensionTypeProvider`, `ICloudBlobStreamBinder<T>`)
> Changes to ExtensionTypeProvider 

- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/ILoggerTests.cs
- test/Microsoft.Azure.WebJobs.Host.TestCommon/LogMessage.cs
- test/Microsoft.Azure.WebJobs.Host.TestCommon/TestHelpers.cs
- test/Microsoft.Azure.WebJobs.Host.TestCommon/TestLogger.cs
- test/Microsoft.Azure.WebJobs.Host.TestCommon/TestLoggerProvider.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/FunctionExecutorTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Filters/FunctionFilterTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Indexers/FunctionIndexerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/JobHostTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Listeners/FunctionListenerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Listeners/HostListenerFactoryTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Singleton/SingletonManagerTests.cs
This fixes some flakiness while reading from log collections while they may still be getting populated by the host. We've fixed this in other branches and must have missed it here.
> improving TestLogger against race conditions

- appveyor.yml
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs
In the `AsyncChain...` e2e tests, there are two tests in the chain that go:
1. Add message to queue and write blob.
2. Trigger off of queue message inserted in 1 and read blob from 1.
Because the queue message was inserted first, there was a chance that the next function started before the blob write had completed. That function could throw a 404 on the missing blob and then re-run successfully. For most of the e2e tests, this was fine as they only cared whether the full chain of functions completed successfully. However, the `AggregatorOnly` test was looking at the aggregation events. It'd see that failed-and-retried function and fail because it was unexpected.
Branch `v2.x` has this same problem. Will be following up there as well.
> removing e2e test race condition

- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AzureStorageEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ServiceBusEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/DispatchQueueTests.cs
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/ILoggerTests.cs
- test/Microsoft.Azure.WebJobs.Host.TestCommon/TestTraceWriter.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Bindings/TraceWriter/TextWriterTraceAdapterTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/CompositeTraceWriterTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/FunctionExecutorTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/FunctionInstanceTraceWriterTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Indexers/FunctionIndexerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/JobHostTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Listeners/FunctionListenerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Listeners/HostListenerFactoryTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/TraceWriterFunctionInstanceLoggerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Singleton/SingletonManagerTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/Config/EventHubConfigurationTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/Config/ServiceBusExtensionConfigTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/UtilityTests.cs
`TestTraceWriter` had similar issues to `TestLogger` -- it'd occasionally throw when enumerating and adding from different threads simultaneously. Example: https://ci.appveyor.com/project/appsvc/azure-webjobs-sdk-rqm4t/build/11349/tests
This pulls the changes made a while back to `TestTraceWriter` in `azure-functions-host`: https://github.com/Azure/azure-functions-host/blob/ba9c1fdb921ac75ef7320da3cb2cdc5fb8e7fbde/test/WebJobs.Script.Tests.Shared/TestTraceWriter.cs
> improving TestTraceWriter

- src/Microsoft.Azure.WebJobs.Logging/Internal/LogWriter.cs
- test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/LoggerTest.cs
Resolves https://github.com/Azure/azure-functions-host/issues/2690
There's two main changes here:
1. When the background flusher hits an error, clear out the task so that it is resumed later (otherwise no more background flushes occur).
2. Set a upper limit on how many entries will be buffered so that if there are errors in flush for a long period of time (say a storage key was rolled over), there is an upper bound on how much memory will be consumed.
webjobs v2.x port is here:
https://github.com/Azure/azure-webjobs-sdk/pull/1762
> Fix LogWriter memory leak and resiliency (webjobs V3.x)

- WebJobs.proj
- appveyor.yml
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsightsEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/LoggerTest.cs
- test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/Properties/AssemblyInfo.cs
- test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/WebJobs.Logging.FunctionalTests.csproj
- tools/SkipStrongNames.xml
After a bunch of debugging, I enabled fusion logs on the Appveyor VM and saw that we weren't skipping strong name validation on this assembly. Tracked it back to the SkipStrongNames.xml file. Now all should be building and running.
> adding Logging.FunctionalTests to build

- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsHostBuilderExtensions.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobs.Logging.ApplicationInsights.csproj
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsConfigurationTests.cs
This change adds ApplicaitonInsights heartbeats.
Heartbeat is a simple custom event, sent to customer ApplicationInsights resource every 15 minutes with infrastructure information such as OS,  runtime version, and app-service details: service name, stamp, owner and host.
this information 
1. allows navigating from Application Map directly to Function/App Service resource 
2. measure application insights usage
/cc @fabiocav  @brettsam
> Enable Application Insights heartbeats

- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLoggerProvider.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/FilteringTelemetryProcessor.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobsTelemetryInitializer.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ApplicationInsightsEndToEndTests.cs
Fixes an issue where the QuickPulseModule was not initialized yet we were starting our test scenario. Now we'll wait until we've gotten the initial ping and first empty sample before continuing.
Also did some minor unrelated code cleanup wherever I was seeing Intellisense messages.
> fixing QuickPulse test; minor code cleanup

- Build.ps1
Small update to allow passing output directory and local publishing (adds build timestamp) flag to the build process. This makes the process of populating a local package source a little easier.
> Updating build file to ease local package publishing

- src/Microsoft.Azure.WebJobs.Extensions.EventHubs/WebJobs.EventHubs.csproj
- src/Microsoft.Azure.WebJobs.Extensions.Storage/WebJobs.Extensions.Storage.csproj
- src/Microsoft.Azure.WebJobs.Host.Storage/WebJobs.Host.Storage.csproj
- src/Microsoft.Azure.WebJobs.ServiceBus/WebJobs.ServiceBus.csproj
Noticed that this was incorrectly setup. Updating so the packages don't show up to consumers.
> Making sure StyleCop NuGet dependency is marked as private

- src/Microsoft.Azure.WebJobs.Extensions.EventHubs/EventHubExtensionConfigProvider.cs
- src/Microsoft.Azure.WebJobs.Extensions.Storage/AzureStorageWebJobsStartup.cs
- src/Microsoft.Azure.WebJobs.Extensions.Storage/Blobs/Config/BlobsExtensionConfigProvider.cs
- src/Microsoft.Azure.WebJobs.Extensions.Storage/Queues/Config/QueuesExtensionConfigProvider.cs
- src/Microsoft.Azure.WebJobs.Extensions.Storage/Tables/Config/TablesExtensionConfigProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Hosting/IWebJobsStartup.cs
- src/Microsoft.Azure.WebJobs.Host/Hosting/WebJobsStartupAttribute.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Config/ServiceBusExtensionConfigProvider.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Config/ServiceBusHostBuilderExtensions.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/Triggers/MessageValueProvider.cs
- src/Microsoft.Azure.WebJobs/ExtensionAttribute.cs
- test/Microsoft.Azure.WebJobs.EventHubs.UnitTests/PublicSurfaceTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Hosting/WebJobsStartupTests.cs
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/PublicSurfaceTests.cs
- test/Microsoft.Azure.Webjobs.Extensions.Storage.UnitTests/PublicSurfaceTests.cs
- test/Microsoft.Azure.Webjobs.Extensions.Storage.UnitTests/Queues/QueueListenerTests.cs
We didn't really want IExtensionConfigProviders to have to be public just for tooling discovery. This actually was problematic in a couple cases (Blobs/Queues) where these couldn't be made public due to the fact that the ctors for the config providers referenced non-public types injected via DI. That will be a general problem for people wishing to leverage DI for their config providers.
So instead I'd like to move to the pattern where it's the WebJobsStartup class for an extension that is annotated. The runtime already discovers these and runs them to register extensions, so these really do define the extensions that are installed at runtime. So for the tooling issue https://github.com/Azure/azure-functions-host/issues/3186 I'll update the tooling to instead search for WebJobsStartup …
> ExtensionAttribute pattern refinements (#3186)

- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Extensions/ApplicationInsightsServiceCollectionExtensions.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsConfigurationTests.cs
As discussed in https://github.com/Azure/azure-webjobs-sdk/pull/1801, TelemetryConfiguration.Active is static singleton that is used by customers to report telemetry manually from the custom code.
Static singletons do not work well with the disposable hosts and DI. We should not initialize Active and instead, to provide the way for users to report telemetry in a consistent matter, we should provide access to TelemtryConfiguration registered in DI container.
This change removes Active initialization. it will still work to the same extent as in V1: it will report telemetry, but no quick pulse. AI config applied by the host (telemetry initializers) will not affect Active. 
Correlation should still work automagically.
> Do not setup Active TelemetryConfiguration

- src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/Constants/LogConstants.cs
- src/Microsoft.Azure.WebJobs.Host/Utility.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Extensions/ApplicationInsightsServiceCollectionExtensions.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobs.Logging.ApplicationInsights.csproj
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobsTelemetryInitializer.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/WebJobs.ServiceBus.csproj
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ApplicationInsightsEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/HttpDependencyCollectionTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ServiceBusRequestAndDependencyCollectionTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/TelemetryValidationHelpers.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ServiceBusEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/WebJobs.Host.EndToEndTests.csproj
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/WebJobs.Host.FunctionalTests.csproj
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsConfigurationTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj
- test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/WebJobs.Logging.FunctionalTests.csproj
- test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/WebJobs.ServiceBus.UnitTests.csproj
- test/Microsoft.Azure.Webjobs.Extensions.Storage.UnitTests/WebJobs.Extensions.Storage.UnitTests.csproj
This change enables ServicBus calls tracking
ApplicaitonInsights listens to ServiceBus SDK events and tracks requests automatically, enriching them with ServiceBus specific properties such as endpoint, queue name, function called (Send/Process)
Such events are translated to telemetry so that 'Send' is tracked as dependency and 'Process' is a request. 
ServiceBus SDK also ensures that is there is a trace context in the message, it will be used.
There is a small caveat with request tracking: AppInsights SDK tracks request from SB automatically and therefore Request tracked by webjobs SDK, in this case, is not needed.
Based on the presence of Activity.Current, we can say whether someone tracks request already and avoid double-tracking.
We've had an offline conversation with @brettsam about …
>  Enable ServiceBus dependency and request collection

- src/Microsoft.Azure.WebJobs.Extensions.EventHubs/Extensions/SystemPropertiesCollectionExtensions.cs
- test/Microsoft.Azure.WebJobs.EventHubs.UnitTests/EventHubTests.cs
Populate SystemProperties on binding data with same property names as used in [EventData SystemPropertiesCollection](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.eventdata.systempropertiescollection?view=azure-dotnet)
Implementation of SystemPropertiesCollection in Microsoft.Azure.Eventhubs changed from v 1.0.3 to 2.1.0.
Here is the reference to SystemPropertiesCollection from .Net reflector
```
public sealed class SystemPropertiesCollection : Dictionary<string, object>
{
internal SystemPropertiesCollection()
{
}
public long SequenceNumber
{
get
{
object obj2;
if (base.TryGetValue("x-opt-sequence-number", ref obj2))
{
return (long) obj2;
}
object[] args = new object[] { "x-opt-sequence-number" };
throw new …
```
> Populate SystemProperties on binding data

- src/Microsoft.Azure.WebJobs.Host/Filters/FunctionExceptionContext.cs
- src/Microsoft.Azure.WebJobs.Host/Filters/FunctionExceptionFilterAttribute.cs
- src/Microsoft.Azure.WebJobs.Host/Filters/FunctionExecutedContext.cs
- src/Microsoft.Azure.WebJobs.Host/Filters/FunctionExecutingContext.cs
- src/Microsoft.Azure.WebJobs.Host/Filters/FunctionFilterContext.cs
- src/Microsoft.Azure.WebJobs.Host/Filters/FunctionInvocationContext.cs
- src/Microsoft.Azure.WebJobs.Host/Filters/FunctionInvocationFilterAttribute.cs
- src/Microsoft.Azure.WebJobs.Host/Filters/IFunctionExceptionFilter.cs
- src/Microsoft.Azure.WebJobs.Host/Filters/IFunctionFilter.cs
- src/Microsoft.Azure.WebJobs.Host/Filters/IFunctionInvocationFilter.cs
After all the recent DI changes, we realize that the Filters APIs need rework to integrate with DI. We'll apply Obsolete to these and reserve the right to make breaking changes to these APIs in upcoming minor versions as we complete the feature.
> Apply Obsolete to Filters feature APIs

- src/Microsoft.Azure.WebJobs.Extensions.EventHubs/EventHubAttribute.cs
- src/Microsoft.Azure.WebJobs.Extensions.EventHubs/EventHubTriggerAttribute.cs
- src/Microsoft.Azure.WebJobs.Extensions.EventHubs/Triggers/EventHubTriggerAttributeBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Bindings/AttributeCloner.cs
- src/Microsoft.Azure.WebJobs.Host/Bindings/BindingProviders/AsyncCollectorBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Bindings/BindingProviders/BindToInputBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Bindings/BindingProviders/BindToStreamBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Bindings/BindingProviders/FilteringBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Bindings/BindingProviders/GenericCompositeBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Bindings/BindingProviders/ItemBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Bindings/BindingProviders/ValidatingWrapperBindingProvider.cs
- src/Microsoft.Azure.WebJobs.Host/Config/ExtensionConfigContext.cs
- src/Microsoft.Azure.WebJobs.Host/Config/FluentBindingRule.cs
- src/Microsoft.Azure.WebJobs.Host/ConfigurationUtility.cs
- src/Microsoft.Azure.WebJobs.Host/DefaultExtensionRegistryFactory.cs
- src/Microsoft.Azure.WebJobs.Host/DefaultNameResolver.cs
- src/Microsoft.Azure.WebJobs.Host/Extensions/IConfigurationExtensions.cs
- src/Microsoft.Azure.WebJobs.Host/Extensions/IExtensionRegistryExtensions.cs
- src/Microsoft.Azure.WebJobs/ConnectionStringAttribute.cs
- test/Microsoft.Azure.WebJobs.Extensions.ServiceBus.UnitTests/Listeners/ServiceBusQueueListenerFactoryTests.cs
- test/Microsoft.Azure.WebJobs.Extensions.ServiceBus.UnitTests/Triggers/ServiceBusSubscriptionListenerFactoryTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ServiceBusRequestAndDependencyCollectionTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/EventHubEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ServiceBusEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/AttributeClonerTests.cs
- test/Microsoft.Azure.WebJobs.Host.TestCommon/TestConfigurationBuilderExtensions.cs
- test/Microsoft.Azure.WebJobs.Host.TestCommon/TestHelpers.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/AttributeClonerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/ExtensionConfigContextTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs
Allows binding attributes to set `[ConnectionString]` (as opposed to `[AppSetting]`, which instructs the attribute cloner to look up the key with `IConfiguration.GetConnectionString()` first, before falling back to the root configuration.
> Adding support for [ConnectionString] attribute on binding attribute properties

- src/Microsoft.Azure.WebJobs.Extensions.Storage/Queues/QueueCausalityManager.cs
- src/Microsoft.Azure.WebJobs.Protocols/JsonSerialization.cs
- src/Microsoft.Azure.WebJobs.Protocols/PersistentQueueReader.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Protocols/JsonSerializationTests.cs
Adding try behavior when loading JObject to improve user experience with respect to #1702.
> Adding try behavior for loading json reader

- src/Microsoft.Azure.WebJobs.Host/Config/JobHostFunctionTimeoutOptions.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs
- src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexProvider.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs
We weren't passing the default timeout values into our Executor. This means that any changes to `JobHostFunctionTimeoutOptions` wasn't honored. This is how functions handles precompiled timeouts, so it's a bug that needs fixing.
Note that there's a handful of formatting fixes that VS auto-performed for me (removing `this.` and removing unnecessary casts). I love getting these in when I can, but let me know if I need to back them out.
> fixing JobHostFunctionTimeoutOptions usage

- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLoggerOptions.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Extensions/ApplicationInsightsServiceCollectionExtensions.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsConfigurationTests.cs
See https://github.com/Azure/azure-webjobs-sdk/issues/1349
This change allows configuring QuickPulse AuthentificationApiKey to secure livestream channel: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-live-stream#secure-the-control-channel
> Add QuickPulse Api Key to AppInsights settings and apply it

- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Initializers/WebJobsTelemetryInitializer.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ServiceBusRequestAndDependencyCollectionTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/TelemetryValidationHelpers.cs
Because of https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/1038 some ServiceBus requests do not have operation name set to function name.
This happens because AppInsights stops the Activity prematurely. It will be fixed in the next ApplicationInsights SDK release.
This change provides workaround for this issue. It could be safely removed with update of AI SDK.
> Fix default operation name on ServiceBus requests

- src/Microsoft.Azure.WebJobs.Host/DefaultExtensionRegistry.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/CompositeFunctionEventCollector.cs
- src/Microsoft.Azure.WebJobs.Host/Executors/JobHostContext.cs
- src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/Aggregator/FunctionResultAggregator.cs
- src/Microsoft.Azure.WebJobs.Host/Queues/Listeners/SharedQueueWatcher.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubConfiguration.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubListener.cs
- src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubTriggerAttributeBindingProvider.cs
- src/Packages/Packages.csproj
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/CompositeFunctionEventCollectorTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/JobHostContextTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj
Should fix https://github.com/Azure/azure-functions-host/issues/2907. There's 3 issues being fixed here:
We were never disposing the Aggregator, which uses a timer with a callback to itself. It implemented IDisposable, but we never called it.
ConcurrentBag stores objects in ThreadLocal storage to highly optimize for same thread read/writes. That’s interesting, but doesn’t explain why the objects are not getting collected.
So now I’m suspecting that we’re hitting this -- https://github.com/dotnet/corefx/issues/23068 (the issue is in the .NET Core repo, but I’d expect that the behavior is the same in full framework). Our object graphs in these bags is huge due to the captured ScriptHost. So I’m pretty certain we’ve got a circular reference in there that’s preventing these objects from …
> Fixing memory leaks

- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Extensions/ApplicationInsightsServiceCollectionExtensions.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsConfigurationTests.cs
ApplicationInsights SDK sends heartbeat events that are used on the AppMap to map node to the particular Azure resource. Cloud role name was missing on heartbeats, so mapping was not possible.
This change ensures proper telemetry initializer that sets role name is added to TeletmryConfiguration.Active.
> Fix missing cloud role name on the heartbeats

- src/Microsoft.Azure.WebJobs.Core.NuGet/WebJobs.Core.nuspec
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights.NuGet/WebJobs.Logging.ApplicationInsights.nuspec
- src/Microsoft.Azure.WebJobs.Logging.NuGet/WebJobs.Logging.nuspec
- src/Microsoft.Azure.WebJobs.NuGet/WebJobs.nuspec
- src/Microsoft.Azure.WebJobs.ServiceBus.NuGet/WebJobs.ServiceBus.nuspec
- tools/NuGetProj.settings.targets
Fixes required to conform to new rules [here](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki?wikiVersion=GBwikiMaster&pagePath=%2FProduct%20Development%20Reference%2FNuGet%2FPublishing%20a%20NuGet%20package&anchor=troubleshooting-package-publishing-errors). We've already made these changes for v3.
> Fixing Package metadata

- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLoggerOptions.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLoggerProvider.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Extensions/ApplicationInsightsLoggingBuilderExtensions.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Extensions/ApplicationInsightsServiceCollectionExtensions.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ISdkVersionProvider.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Initializers/WebJobsTelemetryInitializer.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobs.Logging.ApplicationInsights.csproj
- test/Microsoft.Azure.WebJobs.Extensions.ServiceBus.UnitTests/WebJobs.Extensions.ServiceBus.UnitTests.csproj
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ApplicationInsightsEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/HttpDependencyCollectionTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ServiceBusRequestAndDependencyCollectionTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/TelemetryValidationHelpers.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/WebJobs.Host.EndToEndTests.csproj
- test/Microsoft.Azure.WebJobs.Host.FunctionalTests/WebJobs.Host.FunctionalTests.csproj
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsConfigurationTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/FilteringTelemetryProcessorTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj
- test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/WebJobs.Logging.FunctionalTests.csproj
- test/Microsoft.Azure.Webjobs.Extensions.Storage.UnitTests/WebJobs.Extensions.Storage.UnitTests.csproj
This change brings correlation with upstream services for HttpTrigger.
ApplicationInsights is configured to:
- collect Http requests with extra info like URL and status code
- support W3C distributed tracing protocol 
Related to https://github.com/Azure/azure-functions-host/issues/2447
> Enable AppInsights http requests collection and W3C distributed tracing support

- Build.ps1
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Extensions/ApplicationInsightsServiceCollectionExtensions.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ISdkVersionProvider.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Initializers/WebJobsTelemetryInitializer.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ApplicationInsightsEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/HttpDependencyCollectionTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ServiceBusRequestAndDependencyCollectionTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/TelemetryValidationHelpers.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsConfigurationTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs
Fixes #2012. 
Also re-adds `ISdkVersionProvider` from the reverted Http tracking commit, as it's a better way for us to update the version in multiple places.
> [AppInsights] fixing SB result-reporting

- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Extensions/ApplicationInsightsServiceCollectionExtensions.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsConfigurationTests.cs
When we set up Active config, we  check that instrumentation key is set and do nothing if it is set.
However, ikey is read automatically from the environment variable, i.e. we don't set up WebJobsRoleEnvironmentTelemetryInititalizer. 
So telemetry (heartbeats) that is reported using Active config does not have rolename and instance info.
> Fix TelemetryConfiguration.Active setup to fix rolename and instancename on heartbeats

- src/Microsoft.Azure.WebJobs.Host/Queues/QueueProcessor.cs
We get into some scenarios where a function modifies a QueueMessage itself and we are unable to delete it. That can potentially result in retries that are unexpected. We currently log nothing when we fail to delete a message so it's hard to track down.
> [QueueTrigger] adding debug logs if message cannot be deleted

- src/Microsoft.Azure.WebJobs.Extensions.EventHubs/Listeners/EventHubListener.cs
- test/Microsoft.Azure.WebJobs.Extensions.EventHubs.UnitTests/EventHubListenerTests.cs
- test/Microsoft.Azure.WebJobs.Extensions.EventHubs.UnitTests/EventHubTests.cs
Fixes #2125 
Fixes #1947 
This is effectively moving the behavior from https://github.com/Azure/azure-webjobs-sdk/pull/1788 to `dev`.
> [EventHubs] changing 'rebalancing' errors to be logged as Info

- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Extensions/ApplicationInsightsServiceCollectionExtensions.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Initializers/MetricSdkVersionTelemetryInitializer.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ApplicationInsightsEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsConfigurationTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/PerfCounterSdkVersionTelemetryInitializerTest.cs
This is repeat of https://github.com/Azure/azure-webjobs-sdk/pull/2183, as the old one git branch got into a state I am not sure how to recover from :(
> Modified metric telemetry to have f_ prefix to identify the source of telemetry as functions.

- src/Microsoft.Azure.WebJobs.Extensions.Storage/Blobs/Listeners/ScanBlobScanLogHybridPollingStrategy.cs
- test/Microsoft.Azure.Webjobs.Extensions.Storage.UnitTests/Blobs/Listeners/ScanBlobScanLogHybridPollingStrategyTests.cs
Fixes #2194.
This means we'll be hitting the blob receipts more than previously as we'll always be re-checking the previous timestamp. But the alternative is missing blobs, so it's worth it.
Tests needed tweaking b/c they didn't expect to see a blob a second time. Had to introduce some receipt logic in the unit tests to account for this.
I'm creating this as a draft because I want some early eyes on it -- but I want to add some more logging to this flow before committing this.
> [BlobTrigger] include blobs at previous timestamp to account for rounding

- sample/SampleHost/Program.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Extensions/ApplicationInsightsLoggingBuilderExtensions.cs
- src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobs.Logging.ApplicationInsights.csproj
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ApplicationInsightsEndToEndTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/HttpDependencyCollectionTests.cs
- test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ServiceBusRequestAndDependencyCollectionTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsConfigurationTests.cs
- test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs
Updating App Insights nugets -- which also brought along a new extension method `AddApplicationInsights()`, which conflicts with ours. To make this more straightforward, I've marked this obsolete and renamed it `AddApplicationInsightsWebJobs`.
> updating AppInsights nugets

- build/common.props
Moving core nugets to 3.0.11; ~~trying to debug a nuget restore issue that happens intermittently.~~ Figured out the issue -- we had a rogue package in azure-appservice and nuget doesn't respect ordering in nuget.config. Instead, it loads the first one that replies back! So we were getting a bunch of random build failures. I've hidden the rogue package.
> bumping build version
