src/Dashboard/App_Start/AppModule.cs
src/Dashboard/FastTable/FastTableReader.cs
src/Dashboard/FastTable/NullFastReader.cs
src/Microsoft.Azure.WebJobs.Logging/Entities/FunctionDefinitionEntity.cs
src/Microsoft.Azure.WebJobs.Logging/IFunctionDefinition.cs
src/Microsoft.Azure.WebJobs.Logging/ILogReader.cs
src/Microsoft.Azure.WebJobs.Logging/Internal/ContainerActiveLogger.cs
src/Microsoft.Azure.WebJobs.Logging/Internal/LogReader.cs
src/Microsoft.Azure.WebJobs.Logging/WebJobs.Logging.csproj
test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/LoggerTest.cs

Fix:
https://github.com/Azure/azure-webjobs-sdk/issues/671
https://github.com/Azure/azure-webjobs-sdk/issues/676

Fix logging bugs

---

src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubTriggerInputBindingStrategy.cs
test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/EventHubTests.cs
test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/WebJobs.ServiceBus.UnitTests.csproj

Fix event hub invoke

---

src/Microsoft.Azure.WebJobs.Host/Blobs/Listeners/BlobListener.cs
src/Microsoft.Azure.WebJobs.Host/Blobs/Listeners/BlobListenerFactory.cs
src/Microsoft.Azure.WebJobs.Host/Blobs/Listeners/BlobQueueTriggerExecutor.cs
src/Microsoft.Azure.WebJobs.Host/Blobs/Listeners/ScanBlobScanLogHybridPollingStrategy.cs
src/Microsoft.Azure.WebJobs.Host/Blobs/Listeners/SharedBlobListenerFactory.cs
src/Microsoft.Azure.WebJobs.Host/Blobs/Triggers/BlobTriggerAttributeBindingProvider.cs
src/Microsoft.Azure.WebJobs.Host/Blobs/Triggers/BlobTriggerBinding.cs
src/Microsoft.Azure.WebJobs.Host/Executors/JobHostContextFactory.cs
src/Microsoft.Azure.WebJobs.Host/Indexers/DefaultTriggerBindingProvider.cs
src/Microsoft.Azure.WebJobs.Host/Singleton/SingletonListener.cs
src/Microsoft.Azure.WebJobs.Host/Singleton/SingletonManager.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/BlobBindingEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/BlobTriggerTests.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/BlobTriggerTests.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/Blobs/Listeners/ScanBlobScanLogHybridPollingStrategyTests.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/FunctionalTest.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/ScenarioTests.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/TestDoubles/MemoryBlobStore.cs
test/Microsoft.Azure.WebJobs.Host.TestCommon/JobHostFactory.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/FunctionIndexerFactory.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/JobHostTests.cs

Done in collaboration with @shobak101  (his work was in branch https://github.com/Azure/azure-webjobs-sdk/tree/singletonListener)

Making the shared blob listener a Singleton (#685)

---

src/Microsoft.Azure.WebJobs.Host/Queues/StorageQueueMessageExtensions.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AzureStorageEndToEndTests.cs

improving queue trigger handling of invalid messages

---

src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubConfiguration.cs

Allowing the user to specify their own EventProcessorOptions.

Making EventHubConfiguration more user configurable

---

src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ParallelExecutionTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/FunctionExecutorTests.cs

Behavior for timeouts and cancellations (such as host stopping) are now:
If a timeout:
-	if not `ThrowOnTimeout`, we wait forever for the task to exit after cancelling the token that we passed to the function. This is how it behaved before my change.
-	if `ThrowOnTimeout`, we throw right away, which will bubble up and provide a grace period before calling the host.Stop().
If a cancellation (Stop/Shutdown):
-	 We continue to wait for the original invocation along with the timeout. If a timeout fires, we behave as above.
I had previously added logic that prevented functions from running forever -- we'd exit the Executor and report failure if the host was stopping or there was a timeout. This restores the original behavior and the only difference arises when you set …

fixing executor logic

---

src/Microsoft.Azure.WebJobs.Logging/Entities/ContainerActiveEntity.cs
src/Microsoft.Azure.WebJobs.Logging/Internal/CloudTableInstanceCountLogger.cs
src/Microsoft.Azure.WebJobs.Logging/Internal/ContainerActiveLogger.cs
src/Microsoft.Azure.WebJobs.Logging/Internal/LogReader.cs
src/Microsoft.Azure.WebJobs.Logging/Internal/LogWriter.cs
src/Microsoft.Azure.WebJobs.Logging/Internal/Utility.cs
test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/LoggerTest.cs
test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/SafeCreateTests.cs
test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/WebJobs.Logging.FunctionalTests.csproj

Logging will recreate the table if it's deleted. 
Fix https://github.com/Azure/azure-webjobs-sdk/issues/708

resilient to table getting deleted.

---

src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs

https://github.com/Azure/azure-webjobs-sdk/issues/833

Include parameters on the Fast-logging log start path.

---

src/Microsoft.Azure.WebJobs.Logging.NuGet/WebJobs.Logging.nuspec
test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/LoggerTest.cs
test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/SafeCreateTests.cs
tools/NuGetProj.targets

adding nuspec validation (from other repos) and fixing error; cleaned up warnings

---

src/Dashboard/ApiControllers/FunctionsController.cs

Fix https://github.com/Azure/azure-webjobs-sdk/issues/692

Dashboard - doesn't handle missing ParentId.

---

src/Dashboard/App_Start/AppModule.cs
src/Dashboard/Dashboard.csproj
src/Dashboard/FastTable/FastTableReader.cs
src/Dashboard/FastTable/NullIIndexerLogReader.cs
src/Dashboard/FastTable/NullInvoker.cs

Fix "About link" - it was showing indexing errors.
https://github.com/Azure/azure-webjobs-sdk/issues/840
https://github.com/Azure/azure-webjobs-sdk/issues/677

Fix "Search for blobs" link in dashboard.

---

src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubListener.cs

Fix https://github.com/Azure/azure-webjobs-sdk/issues/870

EventHub checkpointing bug

---

src/Microsoft.Azure.WebJobs.Host/Blobs/Bindings/BlobAttributeBindingProvider.cs
src/Microsoft.Azure.WebJobs.Host/Blobs/Bindings/CloudBlobEnumerableArgumentBindingProvider.cs
src/Microsoft.Azure.WebJobs.Host/Blobs/Bindings/StorageBlobContainerExtensions.cs
src/Microsoft.Azure.WebJobs.Host/Blobs/Bindings/WriteBlobArgumentBinding.cs
src/Microsoft.Azure.WebJobs.Host/Blobs/Listeners/BlobQueueTriggerExecutor.cs
src/Microsoft.Azure.WebJobs.Host/Blobs/StorageBlobToCloudAppendBlobConverter.cs
src/Microsoft.Azure.WebJobs.Host/Blobs/Triggers/BlobTriggerAttributeBindingProvider.cs
src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj
src/Microsoft.Azure.WebJobs.Storage/Blob/IStorageAppendBlob.cs
src/Microsoft.Azure.WebJobs.Storage/Blob/IStorageBlobContainer.cs
src/Microsoft.Azure.WebJobs.Storage/Blob/StorageAppendBlob.cs
src/Microsoft.Azure.WebJobs.Storage/Blob/StorageBlobContainer.cs
src/Microsoft.Azure.WebJobs.Storage/Blob/StorageBlobType.cs
src/Microsoft.Azure.WebJobs.Storage/WebJobs.Storage.csproj
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/BlobBindingEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/HostCallTests.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/TestDoubles/FakeStorageAppendBlob.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/TestDoubles/FakeStorageBlobContainer.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/TestDoubles/MemoryBlobStore.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/TestDoubles/MemoryCloudAppendBlobStream.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/WebJobs.Host.FunctionalTests.csproj

supporting append blobs in blob triggers

---

src/Microsoft.Azure.WebJobs.Logging/Internal/LogReader.cs

Tactical fix for https://github.com/Azure/azure-webjobs-sdk/issues/929
Proper fix comes once https://github.com/projectkudu/AzureFunctionsPortal/issues/634is fixed and then we can remove the whole function.

Fix timeout, #929

---

perf/Microsoft.Azure.WebJobs.Perf/WebJobs.Perf.csproj
src/Dashboard/Dashboard.csproj
src/Microsoft.Azure.WebJobs.Host/Executors/DefaultStorageCredentialsValidator.cs
src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj
src/Microsoft.Azure.WebJobs.Logging/Internal/LogReader.cs
src/Microsoft.Azure.WebJobs.Logging/WebJobs.Logging.csproj
src/Microsoft.Azure.WebJobs.Protocols/WebJobs.Protocols.csproj
src/Microsoft.Azure.WebJobs.ServiceBus/WebJobs.ServiceBus.csproj
src/Microsoft.Azure.WebJobs.Storage/WebJobs.Storage.csproj
src/Microsoft.Azure.WebJobs/WebJobs.csproj
test/Dashboard.UnitTests/Dashboard.UnitTests.csproj
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/WebJobs.Host.EndToEndTests.csproj
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/WebJobs.Host.FunctionalTests.csproj
test/Microsoft.Azure.WebJobs.Host.TestCommon/WebJobs.Host.TestCommon.csproj
test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj
test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/WebJobs.Logging.FunctionalTests.csproj
test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/WebJobs.ServiceBus.UnitTests.csproj

Gonna go ahead and merge this, but creating a PR in case anyone wants an easy way to comment on something I missed.

removing C# 5 restriction; fixing FxCop errors

---

src/Microsoft.Azure.WebJobs.Host/Executors/JobHostContextFactory.cs

I'm committing this ASAP to make sure the build is green -- feel free to comment.

fixing bug in release builds

---

src/Microsoft.Azure.WebJobs.Host/Blobs/Listeners/BlobLogListener.cs
src/Microsoft.Azure.WebJobs.Host/Blobs/Listeners/StorageAnalyticsLogEntry.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Blobs/Listeners/BlobLogListenerTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Blobs/Listeners/StorageAnalyticsLogEntryTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj

Return null (rather than throw) if blob log cannot be parsed

---

test/Microsoft.Azure.WebJobs.Host.FunctionalTests/TableTests.cs

Add tests for { } support ion [Table] TableName property.
No product change.

More regression tests for Table bindings.

---

src/Microsoft.Azure.WebJobs.Host/Bindings/AttributeCloner.cs

Fix null check bug in attribute cloner.

Fix bug in attribute cloner.

---

src/Microsoft.Azure.WebJobs.Host/Blobs/Listeners/SharedBlobQueueListenerFactory.cs
src/Microsoft.Azure.WebJobs.Host/Queues/Listeners/HostMessageListenerFactory.cs
src/Microsoft.Azure.WebJobs.Host/Queues/Listeners/QueueListener.cs
src/Microsoft.Azure.WebJobs.Host/Queues/Listeners/QueueListenerFactory.cs
src/Microsoft.Azure.WebJobs.Host/Queues/QueueProcessor.cs
src/Microsoft.Azure.WebJobs.Host/Queues/QueueProcessorFactoryContext.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Queues/QueueListenerTests.cs

Make MaxPollingInterval configurable for each queue processor

---

src/Microsoft.Azure.WebJobs.Host/Exceptions/FunctionException.cs
src/Microsoft.Azure.WebJobs.Host/Exceptions/RecoverableException.cs
src/Microsoft.Azure.WebJobs.Host/FunctionInvocationException.cs
src/Microsoft.Azure.WebJobs.Host/FunctionTimeoutException.cs
src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexer.cs
src/Microsoft.Azure.WebJobs.Host/Listeners/FunctionListener.cs
src/Microsoft.Azure.WebJobs.Host/Listeners/FunctionListenerException.cs
src/Microsoft.Azure.WebJobs.Host/Listeners/HostListenerFactory.cs
src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ServiceBusEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Listeners/FunctionListenerTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj

Fixed some testing bugs
Previous PR: https://github.com/Azure/azure-webjobs-sdk/pull/1035

Recoverable listener startup exceptions

---

src/Microsoft.Azure.WebJobs.Host/Exceptions/FunctionException.cs
src/Microsoft.Azure.WebJobs.Host/FunctionInvocationException.cs
src/Microsoft.Azure.WebJobs.Host/FunctionTimeoutException.cs

(re)add default exception constructors

---

src/Dashboard/app/views/shared/Errors.html

As discussed with @christopheranderson I've fixed this issue as it's been an outlier for a while.

Update for Issue #893

---

src/Microsoft.Azure.WebJobs.Host/Queues/Triggers/QueueTriggerBinding.cs
src/Microsoft.Azure.WebJobs.ServiceBus/Properties/AssemblyInfo.cs
src/Microsoft.Azure.WebJobs.ServiceBus/Triggers/ServiceBusTriggerBinding.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ServiceBusEndToEndTests.cs
test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/Bindings/ServiceBusTriggerBindingTests.cs
test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/WebJobs.ServiceBus.UnitTests.csproj

Following the exact same pattern that we do for QueueTrigger

Adding ServiceBus default binding data values (#1004)

---

CustomDictionary.xml
src/Microsoft.Azure.WebJobs.Host/Bindings/AttributeCloner.cs
src/Microsoft.Azure.WebJobs/AppSettingAttribute.cs
src/Microsoft.Azure.WebJobs/AutoResolveAttribute.cs
src/Microsoft.Azure.WebJobs/WebJobs.csproj
test/Microsoft.Azure.WebJobs.Host.UnitTests/AttributeClonerTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs

Added AppSettingAttribute

---

src/Microsoft.Azure.WebJobs.Host/Triggers/ITriggerBindingStrategy.cs
src/Microsoft.Azure.WebJobs.Host/Triggers/TriggerArgumentBinding/ArraryTriggerArgumentBinding.cs
src/Microsoft.Azure.WebJobs.Host/Triggers/TriggerArgumentBinding/SimpleTriggerArgumentBinding.cs
src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubTriggerInputBindingStrategy.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/EventHubEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/FakeQueue/FakeQueueTriggerBindingStrategy.cs
test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/EventHubTests.cs

Completes the work started in https://github.com/Azure/azure-webjobs-sdk/pull/1071. Also addresses https://github.com/Azure/azure-webjobs-sdk/issues/1072.

EventHub multi-dispatch binding data support

---

src/Microsoft.Azure.WebJobs.Logging/Entities/ContainerActiveEntity.cs

Remove blocking call in ContainerActiveEntity

---

src/Microsoft.Azure.WebJobs.Host/Storage/IStorageAccountExtensions.cs
src/Microsoft.Azure.WebJobs.Host/Storage/StorageAccountTypeExtensions.cs
src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj
test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/DefaultStorageAccountProviderTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Storage/StorageAccountExtensionsTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj

Add ZRS warning to blob-only accounts

---

src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubTriggerAttribute.cs

resolves #1114 
@MikeStall I'm going to do further work for #1409 and #1410 and to wire up the connection property, but this should get @lindydonna unblocked.

Add event hub connection property

---

src/Microsoft.Azure.WebJobs.ServiceBus/ServiceBusAttribute.cs
src/Microsoft.Azure.WebJobs.ServiceBus/ServiceBusTriggerAttribute.cs

Probably should have a test for this, but not sure how to get all attributes that the host supports in a test.

Add [Binding] attribute to all core attributes.

---

test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AzureStorageEndToEndTests.cs

Related to #985. Not a fix (yet), but makes sure we have a failing test if we accidentally upgrade the project.
Ran this a bunch of times under 7.2.1 and passed every time.
Ran this a bunch of times under 8.x and failed every time.

adding queue test that fails under storage 8.x

---

src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubConfiguration.cs
src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubListener.cs
src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubTriggerAttributeBindingProvider.cs
test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/Listeners/EventHubListenerTests.cs
test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/WebJobs.ServiceBus.UnitTests.csproj

Configurable event hub checkpointing

---

src/Microsoft.Azure.WebJobs.ServiceBus/MessagingProvider.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ServiceBusEndToEndTests.cs
test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/MessagingProviderTests.cs

Fix based on the detailed investigations @brettsam did for https://github.com/Azure/azure-webjobs-sdk/issues/881

ServiceBus MessageFactory caching (#881)

---

src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubConfiguration.cs
test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/EventHubTests.cs

related to https://github.com/Azure/azure-webjobs-sdk-script/issues/1529

Populate event hub configuration from metadata

---

src/Microsoft.Azure.WebJobs.Host/Bindings/AttributeCloner.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/AttributeClonerTests.cs

Improved AppSetting error

---

src/Microsoft.Azure.WebJobs.Host/Blobs/BlobPath.cs
src/Microsoft.Azure.WebJobs.Host/Blobs/BlobPathSource.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Blobs/BlobPathSourceTests.cs

resolves #1136 
resolves https://github.com/Azure/azure-webjobs-sdk-script/issues/1482

Improve blob path error messages

---

src/Microsoft.Azure.WebJobs.Host/Executors/FunctionInstanceFactory.cs
src/Microsoft.Azure.WebJobs.Host/Executors/FunctionInstanceFactoryContext.cs
src/Microsoft.Azure.WebJobs.Host/Executors/FunctionInstanceFactoryContextOfT.cs
src/Microsoft.Azure.WebJobs.Host/Executors/HostMessageExecutor.cs
src/Microsoft.Azure.WebJobs.Host/Executors/IFunctionInstanceFactory.cs
src/Microsoft.Azure.WebJobs.Host/Executors/TriggeredFunctionData.cs
src/Microsoft.Azure.WebJobs.Host/Executors/TriggeredFunctionExecutor.cs
src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexer.cs
src/Microsoft.Azure.WebJobs.Host/JobHost.cs
src/Microsoft.Azure.WebJobs.Host/Triggers/ITriggeredFunctionInstanceFactory.cs
src/Microsoft.Azure.WebJobs.Host/Triggers/TriggeredFunctionInstanceFactory.cs
src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj
test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/TriggeredFunctionExecutorTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj

Alternate proposal to https://github.com/Azure/azure-webjobs-sdk/pull/1167. In this case, a handler can be specified as part of the trigger data.

Invocation interception

---

src/Microsoft.Azure.WebJobs.Host/Bindings/AttributeCloner.cs
src/Microsoft.Azure.WebJobs.Host/Bindings/Path/BindingTemplate.cs
src/Microsoft.Azure.WebJobs.Host/Blobs/BindableBlobPath.cs
src/Microsoft.Azure.WebJobs.Host/Tables/BindableTableEntityPath.cs
src/Microsoft.Azure.WebJobs.Host/Tables/ParameterizedTableEntityPath.cs
src/Microsoft.Azure.WebJobs.Host/Tables/TableClient.cs
src/Microsoft.Azure.WebJobs.Host/Tables/TableExtension.cs
src/Microsoft.Azure.WebJobs.Host/Tables/TableFilterFormatter.cs
src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj
src/Microsoft.Azure.WebJobs/TableAttribute.cs
src/Microsoft.Azure.WebJobs/WebJobs.csproj
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/TableTests.cs
test/Microsoft.Azure.WebJobs.Host.TestCommon/TestJobHost.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/AttributeClonerTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj

Resolve https://github.com/Azure/azure-webjobs-sdk/issues/1169
Investigate if we can apply to more things internally in SDK (Table, Blob, Queue)

Add Validation attribute.

---

src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs

Fix log ordering bug.

---

appveyor.yml

https://appveyor.statuspage.io/incidents/m2vdvw39kdk8

Update appveyor hosts for nuget (dev)

---

appveyor.yml

https://github.com/Azure/azure-webjobs-sdk/pull/1238

Update appveyor hosts for nuget (v2.x)

---

src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndex.cs
src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexer.cs
test/Microsoft.Azure.WebJobs.Host.TestCommon/TestJobHost.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Indexers/ReturnValueTests.cs

This should bring Dev up to date with all my v2.x  changes.

Port v2.x changes into Dev

---

src/Microsoft.Azure.WebJobs.Host/Bindings/BindingProviders/FunctionFilterBindingProvider.cs
src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs
src/Microsoft.Azure.WebJobs.Host/Executors/IJobInvoker.cs
src/Microsoft.Azure.WebJobs.Host/FunctionExecutedContext.cs
src/Microsoft.Azure.WebJobs.Host/FunctionExecutingContext.cs
src/Microsoft.Azure.WebJobs.Host/FunctionInvocationContext.cs
src/Microsoft.Azure.WebJobs.Host/IFunctionInvocationFilter.cs
src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexer.cs
src/Microsoft.Azure.WebJobs.Host/InvocationFilterAttribute.cs
src/Microsoft.Azure.WebJobs.Host/InvokeFunctionFilterAttribute.cs
src/Microsoft.Azure.WebJobs.Protocols/FunctionDescriptor.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/InvocationFilterEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/InvocationFilterTests.cs

Invoke Filter cleanup

---

src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/Constants/LogConstants.cs
src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/LoggerExtensions.cs
src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsightsEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/LoggerExtensionsTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs

Fixes #1281 
Fixes #1282
Fixes #1264

[AppInsights] adding a LogMetric ILogger extension; attach custom scope properties

---

src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/Constants/LogConstants.cs
src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/LoggerExtensions.cs
src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsightsEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/LoggerExtensionsTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs

[AppInsights] adding a LogMetric ILogger extension; attach custom scope properties; allow BeginScope to handle FormattedLogValues

---

sample/SampleHost/SampleHost.csproj
sample/SampleHost/appsettings.json

The sample doesn't have appsettings configuration and appropriate project file copy task. So adding it to have a more complete sample project

Adding appsettings so sample shows how to configure storage

---

src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsScope.cs

This is the `v2.x` version of #1301, with an additional test improvement.

moving logic to DictionaryLoggerScope

---

src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs

Moving to AppInsights 2.4 changed how request ids were set when you called `telemetryClient.StartOperation()`. It would give you a new id based on the one you had set, but it would not match exactly. This meant that even though all of the traces for a request were correlated in the App Insights portal UX, they weren't showing up as directly related to the request. Instead, they were showing as part of the root operation (slightly different than before). 
If we use `requestTelemetry.Start()` instead, the request id doesn't get altered and our other important behavior (Profiler support) still works. This changes the start/stop code to use this API instead.
Also cleaned up a few messages I was getting in VS.
This will be ported to `v2.x` as well.

[AppInsights] changing to use requestTelemetry.Start()

---

src/Microsoft.Azure.WebJobs.Host/Blobs/BindableBlobPath.cs
src/Microsoft.Azure.WebJobs.Host/Blobs/BlobPath.cs
src/Microsoft.Azure.WebJobs.Host/Blobs/ParameterizedBlobUrl.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/BlobBindingEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Blobs/BlobPathSourceTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Blobs/BlobPathTests.cs

BlobAttribute supports an absolute blob url(autoresolvable) as blobPath

---

NuGet.Config
appveyor.yml
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/WebJobs.Host.EndToEndTests.csproj

Created this guy: https://github.com/mamaso/appinsights-testlogger/blob/master/Logger.cs
Example stuff:

Add app insights logging to e2e test run

---

src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsightsEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs

[AppInsights] improving Exception logging

---

src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/DefaultTelemetryClientFactory.cs
src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobsRoleEnvironmentTelmetryInitializer.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/DefaultTelemetryClientFactoryTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/WebJobsRoleEnvironmentTelemetryInitializerTests.cs

[AppInsights] changing RoleName calculation to work with Functions slots

---

src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubAsyncCollector.cs
test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/EventHubAsyncCollectorTests.cs

https://github.com/Azure/azure-webjobs-sdk/commit/d6761993973d2f309cdf3684219f455dc2e57cc7 never made it into the dev branch from v2.x

Port Mike's event hub partition key changes to dotnet core

---

src/Microsoft.Azure.WebJobs.Host/Config/FluentBindingRule.cs
src/Microsoft.Azure.WebJobs.Host/Queues/Bindings/QueueBindingProvider.cs

Resolves https://github.com/Azure/azure-webjobs-sdk/issues/1360
Apply to Queue.

Add binding rule for async collectors:

---

src/Microsoft.Azure.WebJobs.Host/ConfigurationUtility.cs
src/Microsoft.Azure.WebJobs.Host/Listeners/HostListenerFactory.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/ConfigurationUtilityTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Listeners/HostListenerFactoryTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/appsettings.json

• Get disabled state from IConfiguration
• Format of the setting: <FunctionName>.Disabled = true.
• Function is enabled by default if there is no setting.
• The <FunctionName>.Disabled setting overwrites [Disable] attribute only if function is disabled.

Disable functions using configuration

---

WebJobs.sln
src/Microsoft.Azure.WebJobs.Host/Executors/StorageAccountParser.cs
src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj
src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/DefaultTelemetryClientFactory.cs
src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobs.Logging.ApplicationInsights.csproj
src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobsSanitizingInitializer.cs
src/Microsoft.Azure.WebJobs.Shared/Sanitizer.cs
src/Microsoft.Azure.WebJobs.Shared/WebJobs.Shared.projitems
src/Microsoft.Azure.WebJobs.Shared/WebJobs.Shared.shproj
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/Queues/QueueTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/DefaultTelemetryClientFactoryTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/WebJobsSanitizingInitializerTests.cs

sanitizing app insights logs

---

appveyor.yml
src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj
src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobs.Logging.ApplicationInsights.csproj
src/Microsoft.Azure.WebJobs.Logging/WebJobs.Logging.csproj
src/Microsoft.Azure.WebJobs.Protocols/WebJobs.Protocols.csproj
src/Microsoft.Azure.WebJobs.ServiceBus/WebJobs.ServiceBus.csproj
src/Microsoft.Azure.WebJobs.Storage/WebJobs.Storage.csproj
test/Microsoft.Azure.WebJobs.EventHubs.UnitTests/WebJobs.EventHubs.UnitTests.csproj
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/WebJobs.Host.EndToEndTests.csproj
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/WebJobs.Host.FunctionalTests.csproj
test/Microsoft.Azure.WebJobs.Host.TestCommon/WebJobs.Host.TestCommon.csproj
test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj
test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/WebJobs.Logging.FunctionalTests.csproj
test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/WebJobs.ServiceBus.UnitTests.csproj

Revving package dependencies for next drop.

Revving dependencies

---

src/Microsoft.Azure.WebJobs.Host/Dispatch/DispatchQueueHandler.cs
src/Microsoft.Azure.WebJobs.Host/Dispatch/IDispatchQueueHandler.cs
src/Microsoft.Azure.WebJobs.Host/Dispatch/IMessageHandler.cs
src/Microsoft.Azure.WebJobs.Host/Dispatch/InMemoryDispatchQueueHandler.cs
src/Microsoft.Azure.WebJobs.Host/Dispatch/SharedQueueHandler.cs
src/Microsoft.Azure.WebJobs.Host/Executors/JobHostConfigurationExtensions.cs
src/Microsoft.Azure.WebJobs.Host/HostQueueNames.cs
src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexProvider.cs
src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexer.cs
src/Microsoft.Azure.WebJobs.Host/JobHostConfiguration.cs
src/Microsoft.Azure.WebJobs.Host/Listeners/ListenerFactoryContext.cs
src/Microsoft.Azure.WebJobs.Host/Listeners/ListenerFactoryListener.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/BlobBindingEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/DispatchQueueEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ExtensionWithDispatchQueue.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/DispatchQueueTests.cs
test/Microsoft.Azure.WebJobs.Host.TestCommon/SimpleQueueConfiguration.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs

migrate sharedQueue change from V2 to V3

---

src/Microsoft.Azure.WebJobs.Host/Bindings/BindingTemplateExtensions.cs
src/Microsoft.Azure.WebJobs.Host/Constants.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/Queues/QueueTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/AttributeClonerTests.cs

Improved binding error message.

---

src/Microsoft.Azure.WebJobs.Host/Singleton/SingletonManager.cs
src/Microsoft.Azure.WebJobs/SingletonAttribute.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Singleton/SingletonManagerTests.cs

Fix for https://github.com/Azure/azure-webjobs-sdk/issues/1457

SingletonAttribute LockAcquisitionTimeout property fix

---

src/Microsoft.Azure.WebJobs.Host/Bindings/OpenType.cs
src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubConfiguration.cs

* Refined OpenType.Poco definition to improve user error experience.

Added POCO-to-EventData converter. Related to issue #1396.

---

src/Microsoft.Azure.WebJobs.Host/Bindings/BindingProviders/AsyncCollectorBindingProvider.cs
src/Microsoft.Azure.WebJobs.Host/IConverterManager.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/JobHostMetadataProviderTests.cs

Fix https://github.com/Azure/azure-webjobs-sdk/issues/1459
Re-add test  that got removed during a merge conflict resolution, GetFunctionMetadata().

Fix QueueTriggerByteArray

---

src/Microsoft.Azure.WebJobs.Shared/Sanitizer.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/WebJobsSanitizingInitializerTests.cs

Porting Fix for [Issue](https://github.com/Azure/azure-webjobs-sdk-script/issues/2188)

Port Sanitizer fix from script repo

---

src/Microsoft.Azure.WebJobs.Shared/Sanitizer.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/ILoggerTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/WebJobsSanitizingInitializerTests.cs

Porting [Sanitizer fix ](https://github.com/Azure/azure-webjobs-sdk-script/issues/2188)from Runtime repo

Fix Sanitizer

---

src/Microsoft.Azure.WebJobs.Host/Loggers/TraceEventExtensions.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/ILoggerTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/FunctionInstanceTraceWriterTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/TraceWriterFunctionInstanceLoggerTests.cs

Add FunctionName in TraceEvent details

---

src/Microsoft.Azure.WebJobs.Host/Loggers/TraceEventExtensions.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/FunctionInstanceTraceWriterTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/TraceWriterFunctionInstanceLoggerTests.cs

Fixing up #1488 for @pragnagopa.

Update FunctionNameKey to use LogName

---

src/Analyzer/WebJobs.VSAnalyzer.Core/WebJobs.VSAnalyzer.Core.csproj
src/Analyzer/WebJobs.VSAnalyzer.Core/packages.config
src/Analyzer/WebJobs.VSAnalyzer.Vsix/Analyzer2.Vsix.csproj

Fixes https://github.com/Azure/azure-webjobs-sdk/issues/1501

Fixed project issues with the Analyzer Projects

---

src/Microsoft.Azure.WebJobs.Host/Constants.cs
src/Microsoft.Azure.WebJobs.Host/Executors/DefaultStorageCredentialsValidator.cs
src/Microsoft.Azure.WebJobs.Host/GlobalSuppressions.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/DefaultStorageCredentialsValidatorTests.cs

* Fixes Azure/azure-webjobs-sdk-script#2237 (v1)
* Corresponding PR for v2 is #1506

Improved error message when running against stopped storage emulator. (v1)

---

src/Microsoft.Azure.WebJobs.Host/Constants.cs
src/Microsoft.Azure.WebJobs.Host/Executors/DefaultStorageCredentialsValidator.cs
src/Microsoft.Azure.WebJobs.Host/GlobalSuppressions.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Executors/DefaultStorageCredentialsValidatorTests.cs

* Fixes Azure/azure-webjobs-sdk-script#2237 (v2)
* Corresponding PR for v1 is #1507

Improved error message when running against stopped storage emulator. (v2)

---

src/Microsoft.Azure.WebJobs.Host/Dispatch/SharedQueueHandler.cs
src/Microsoft.Azure.WebJobs.Host/Listeners/ListenerFactoryContext.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/DispatchQueueTests.cs

https://github.com/Azure/azure-webjobs-sdk/pull/1516
output warning messages to both `ILogger` and `TraceWriter`

delay sharedQueue initialization error (v2.x)

---

src/Microsoft.Azure.WebJobs.Host/Bindings/BindingProviders/TriggerAdapterBindingProvider.cs
src/Microsoft.Azure.WebJobs.Host/Config/DirectInvokeString.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Common/TriggerAdapterTest.cs

Resolves https://github.com/Azure/azure-webjobs-sdk/issues/1523

Fix TriggerAdapter bug

---

src/Microsoft.Azure.WebJobs.Host/Executors/JobHostConfigurationExtensions.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsightsEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/ILoggerTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/JobHostTests.cs

adding warning if ServicePointManager.DefaultConnectionLimit is set to 2

---

src/Microsoft.Azure.WebJobs.Logging/Internal/LogWriter.cs

Fix race in logging.

---

Build.ps1
appveyor.yml

Skipping packaging and exiting with proper code on build failure

---

src/Microsoft.Azure.WebJobs.Host/Queues/Listeners/QueueListener.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Queues/QueueListenerTests.cs

Fix for https://github.com/Azure/azure-webjobs-sdk/issues/770
We currently generate a LOT of exceptions polling non-existent queues. While they are handled internally, it makes local debugging hard if you have "break on all exceptions" set. More importantly (as in the issue) these show up in App Insights. 
To see the issue for yourself, simply set the SampleHost project as the startup project and run with "break on all exceptions" set. You'll see lots :) With these changes, you'll see none.

Don't query non-existent queues (#770)

---

src/Microsoft.Azure.WebJobs.Host/Executors/JobHostConfigurationExtensions.cs
src/Microsoft.Azure.WebJobs.Host/JobHostConfiguration.cs
src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubConfiguration.cs
src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubListener.cs
src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubTriggerAttributeBindingProvider.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/JobHostConfigurationTests.cs
test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/EventHubTests.cs

Add error log from eventhublistener

---

test/Microsoft.Azure.WebJobs.Host.FunctionalTests/HostStopTests.cs

This test expected:
1. Start host.
2. Listener sees queue message and invokes function.
3. Pause function to wait for host to stop.
3. Stop host.
4. Wait for function to continue and validate the cancellation token is canceled.
However, in AppVeyor sometimes this would happen:
1. Start host.
2. Stop host before the listener ever saw the message.
3. Timeout because the function never completed (because it was never started).
So I added a check that lets the function signal back to the test that the function has begun execution. Ran it several thousand times in a loop in AppVeyor and never failed. Previously it'd fail in less than 20 tries.

fixing HostStopTest

---

src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubListener.cs

V2 version of:
https://github.com/Azure/azure-webjobs-sdk/pull/1627

Event Hubs cancellation token fix for batched mode (V2)

---

src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubConfiguration.cs

Fix for https://github.com/Azure/azure-webjobs-sdk/issues/1470

EventHubConfiguration concurrency fix (#1470)

---

sample/SampleHost/Functions.cs
sample/SampleHost/Program.cs
sample/SampleHost/SampleHost.csproj
src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/Constants/LogCategories.cs
src/Microsoft.Azure.WebJobs.ServiceBus/Config/ServiceBusConfiguration.cs
src/Microsoft.Azure.WebJobs.ServiceBus/Config/ServiceBusExtensionConfig.cs
test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/Config/ServiceBusExtensionConfigTests.cs

Merging https://github.com/Azure/azure-webjobs-sdk/pull/1704 to dev. Code is a bit different in dev branch due to API differences.

Exception logging for MessageReceiver background exceptions

---

src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/Constants/LogConstants.cs
src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobsTelemetryInitializer.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs

logging EventId to App Insights

---

src/Microsoft.Azure.WebJobs.Host/Loggers/UpdateOutputLogCommand.cs

If we upload too many blobs at once from different threads, we can end up with an Md5Mismatch error. Ideally, we'd switch these to AppendBlobs but it requires a dashboard update before we can do this. This change ensures that we're only ever uploading the blob from one thread at a time so we won't hit the error.

synchronizing dashboard blob uploads to prevent Md5Mismatch errors

---

test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs

fixing race in e2e test

---

src/Microsoft.Azure.WebJobs.Logging/Internal/LogWriter.cs
test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/LoggerTest.cs
test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/WebJobs.Logging.FunctionalTests.csproj

Webjobs v2.x version of:
https://github.com/Azure/azure-webjobs-sdk/pull/1754

Fix LogWriter memory leak and resiliency (webjobs V2.x) 

---

src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsightsEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs

Fixes https://github.com/Azure/azure-functions-host/issues/2556
This has already been done in `dev` -- backporting it to `v2.x`

AppInsights: Logging trace message for exception

---

test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ApplicationInsightsEndToEndTests.cs

I was having timing issues with this test, so rather than invoke 5 functions and hope they were caught by the QuickPulse module, the test will now loop and make sure *something* is seen by the QuickPulse service. This ensures that we're not filtering away those requests, which is all we're trying to prove. The exact number isn't important.

changing QuickPulse test approach

---

src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs

Fix FunctionExecutor null ref

---

test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsightsEndToEndTests.cs

improving QuickPulse test

---

src/Microsoft.Azure.WebJobs.Extensions.Storage/Queues/QueueProcessor.cs
test/Microsoft.Azure.Webjobs.Extensions.Storage.UnitTests/Queue/QueueProcessorTests.cs

Check queue message dequeue count before executing function.

---

src/Microsoft.Azure.WebJobs.Host/Bindings/ExecutionContext/ExecutionContext.cs
src/Microsoft.Azure.WebJobs.Host/Bindings/ExecutionContext/ExecutionContextBindingProvider.cs
src/Microsoft.Azure.WebJobs.Host/Bindings/ExecutionContext/ExecutionContextOptions.cs
src/Microsoft.Azure.WebJobs.Host/Hosting/WebJobsHostExtensions.cs
src/Microsoft.Azure.WebJobs.Host/Hosting/WebJobsServiceCollectionExtensions.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Bindings/ExecutionContext/ExecutionContextBindingTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs

Migrated to the new DI model and moved this from the extensions project into the SDK. Goal is to get rid of the extensions project and package.

Adding ExecutionContext binding

---

src/Microsoft.Azure.WebJobs.ServiceBus/MessageProcessor.cs
test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/MessageProcessorTests.cs

Merging https://github.com/Azure/azure-webjobs-sdk/pull/1814 to dev

Fixing MessageProcessor AutoComplete handling

---

src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ApplicationInsightsEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs

When we switched the Operation Ids to match with the current Activity Id, we lost the FunctionInvocationId from some of or telemetry. This adds it back to the Properties collection, when it exists.

[AppInsights] Adding InvocationId to the telemetry properties

---

test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ApplicationInsightsEndToEndTests.cs

Porting changes from #1799 to `dev`.

porting QuickPulse test improvements

---

src/Microsoft.Azure.WebJobs.Extensions.EventHubs/WebJobs.EventHubs.csproj
src/Microsoft.Azure.WebJobs.Extensions.Storage/WebJobs.Extensions.Storage.csproj
src/Microsoft.Azure.WebJobs.Host.Storage/WebJobs.Host.Storage.csproj
src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobs.Logging.ApplicationInsights.csproj
src/Microsoft.Azure.WebJobs.Logging/WebJobs.Logging.csproj
src/Microsoft.Azure.WebJobs.ServiceBus/WebJobs.ServiceBus.csproj
test/FakeStorage/Blob/FakeStoragePageBlob.cs
test/FakeStorage/FakeAzureStorage.csproj
test/FakeStorage/TestExtensions.cs
test/Microsoft.Azure.WebJobs.EventHubs.UnitTests/EventHubAsyncCollectorTests.cs
test/Microsoft.Azure.WebJobs.EventHubs.UnitTests/EventHubTests.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/WebJobs.Host.EndToEndTests.csproj
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/WebJobs.Host.FunctionalTests.csproj
test/Microsoft.Azure.WebJobs.Host.TestCommon/WebJobs.Host.TestCommon.csproj
test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/WebJobs.Logging.FunctionalTests.csproj
test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/WebJobs.ServiceBus.UnitTests.csproj
test/Microsoft.Azure.Webjobs.Extensions.Storage.UnitTests/WebJobs.Extensions.Storage.UnitTests.csproj

Also updated WindowsAzure.Storage to v9.3.1
Fixes #1710

Update Microsoft.Azure.EventHubs to 2.1.0

---

src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs

Fixes #1875.
I was using `telemetry.Properties.Add()` to copy `ILogger` Scope and State values into App Insights Telemetry. But both Scope and State values can be `IEnumerable<KeyValuePair<string,object>>`, which means a potential for duplicate keys. 
Now we'll take a "last state wins" approach if we find duplicates. So, add the Scope properties first, then the State properties, updating the value each time, if it's present.

[AppInsights] adding 'last state wins' behavior for scope and state properties

---

src/Microsoft.Azure.WebJobs.Extensions.EventHubs/Config/EventHubExtensionConfigProvider.cs
src/Microsoft.Azure.WebJobs.Extensions.Storage/StorageLoadBalancerQueue.cs
src/Microsoft.Azure.WebJobs.Extensions.Storage/StorageWebJobsBuilderExtensions.cs
src/Microsoft.Azure.WebJobs.Host.Storage/Logging/DashboardLogger.cs
src/Microsoft.Azure.WebJobs.Host/Config/IWebJobsExtensionConfiguration.cs
src/Microsoft.Azure.WebJobs.Host/Config/JobHostFunctionTimeoutOptions.cs
src/Microsoft.Azure.WebJobs.Host/Config/JobHostOptions.cs
src/Microsoft.Azure.WebJobs.Host/Config/WebJobsExtensionConfiguration.cs
src/Microsoft.Azure.WebJobs.Host/Dispatch/HostMessageListenerFactory.cs
src/Microsoft.Azure.WebJobs.Host/Dispatch/ILoadBalancerQueue.cs
src/Microsoft.Azure.WebJobs.Host/Dispatch/SharedQueueHandler.cs
src/Microsoft.Azure.WebJobs.Host/Hosting/WebJobsServiceCollectionExtensions.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/PublicSurfaceTests.cs

Original renames here: https://github.com/Azure/azure-webjobs-sdk/pull/1900

Reverting a few renames :(

---

src/Microsoft.Azure.WebJobs.Extensions.Storage/Queues/Config/QueuesOptions.cs
test/Microsoft.Azure.Webjobs.Extensions.Storage.UnitTests/Queues/QueuesOptionsTests.cs

This is a port of https://github.com/Azure/azure-webjobs-sdk/pull/1569

Allow NewBatchThreshold to be set to 0

---

build/common.props

Invalid copyright notice causing package validation errors.

Fixing copyright notice in common props

---

src/Microsoft.Azure.WebJobs.Host/CompositeTraceWriter.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/CompositeTraceWriterTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/ConsoleTraceWriterTests.cs

Fixes #1533.
I'm suspecting that PR #1567 unmasked this issue. It's likely been hiding behind the other issue and once it was fixed, this one is now getting hit.

Synchronizing the TextWriter in CompositeTraceWriter

---

src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs
src/Microsoft.Azure.WebJobs.Host/Executors/FunctionInstance.cs
src/Microsoft.Azure.WebJobs.Host/Executors/FunctionInstanceFactory.cs
src/Microsoft.Azure.WebJobs.Host/Executors/FunctionInstanceFactoryContext.cs
src/Microsoft.Azure.WebJobs.Host/Executors/IFunctionInstance.cs
src/Microsoft.Azure.WebJobs.Host/Executors/TriggeredFunctionData.cs
src/Microsoft.Azure.WebJobs.Host/Executors/TriggeredFunctionExecutor.cs
src/Microsoft.Azure.WebJobs.Host/GlobalSuppressions.cs
src/Microsoft.Azure.WebJobs.Host/Loggers/TraceWriterFunctionInstanceLogger.cs
src/Microsoft.Azure.WebJobs.Host/Queues/Listeners/QueueTriggerExecutor.cs
src/Microsoft.Azure.WebJobs.Host/Triggers/TriggeredFunctionInstanceFactory.cs
src/Microsoft.Azure.WebJobs.Protocols/FunctionStartedMessage.cs
src/Microsoft.Azure.WebJobs.ServiceBus/Listeners/ServiceBusTriggerExecutor.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ServiceBusEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/FunctionInstanceTraceWriterTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsLoggerTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/TraceWriterFunctionInstanceLoggerTests.cs
test/Microsoft.Azure.WebJobs.ServiceBus.UnitTests/Listeners/ServiceBusListenerTests.cs

Message ID logging for web jobs v2.x. For parity with #1993.

Porting message ID logging to v2.x

---

src/Microsoft.Azure.WebJobs.Extensions.EventHubs/Triggers/EventHubTriggerAttributeBindingProvider.cs
src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Bindings/ServiceBusAttributeBindingProvider.cs
src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Triggers/ServiceBusTriggerAttributeBindingProvider.cs

ServiceBusAccountAttribute - Account parameter %% value not passed. Fixes #1735.

---

src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ApplicationInsightsEndToEndTests.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ServiceBusRequestAndDependencyCollectionTests.cs

logging 'Executed...' before function marked as completed

---

src/Microsoft.Azure.WebJobs.Host/Listeners/HostListenerFactory.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/HostListenerFactoryTests.cs
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/appsettings.json

https://github.com/Azure/azure-functions-host/issues/3889

[Linux] Function still triggers despite being disabled.

---

src/Microsoft.Azure.WebJobs.Host/Hosting/WebJobsHostBuilderExtensions.cs

Add overloads of ConfigureWebJobs to expose HostBuilderContext

---

src/Microsoft.Azure.WebJobs.Extensions.EventHubs/Extensions/SystemPropertiesCollectionExtensions.cs
test/Microsoft.Azure.WebJobs.Extensions.EventHubs.UnitTests/EventHubTests.cs

Add SystemProperties dictionary to binding data

---

src/Microsoft.Azure.WebJobs.Extensions.Storage/Queues/QueueProcessor.cs

[QueueTrigger] adding debug logs if message cannot be deleted

---

src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLoggerOptions.cs
src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Extensions/ApplicationInsightsServiceCollectionExtensions.cs
src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Initializers/WebJobsTelemetryInitializer.cs
src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/NullTelemetryModule.cs
src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobs.Logging.ApplicationInsights.csproj
test/Microsoft.Azure.WebJobs.Extensions.ServiceBus.UnitTests/WebJobs.Extensions.ServiceBus.UnitTests.csproj
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ServiceBusRequestAndDependencyCollectionTests.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/WebJobs.Host.EndToEndTests.csproj
test/Microsoft.Azure.WebJobs.Host.FunctionalTests/WebJobs.Host.FunctionalTests.csproj
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/ApplicationInsightsConfigurationTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/Loggers/FilteringTelemetryProcessorTests.cs
test/Microsoft.Azure.WebJobs.Host.UnitTests/WebJobs.Host.UnitTests.csproj
test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/WebJobs.Logging.FunctionalTests.csproj
test/Microsoft.Azure.Webjobs.Extensions.Storage.UnitTests/WebJobs.Extensions.Storage.UnitTests.csproj

Fix issue https://github.com/Azure/azure-functions-host/issues/3852
Question: do we want to put it under the configuration so users who don't want it could turn it off?

Configure performance counters collection

---

src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Initializers/WebJobsTelemetryInitializer.cs

Computername is not set in Linux consumption

Use container name as role instance name if machine name is not set

---

src/Microsoft.Azure.WebJobs.Host/Bindings/TraceWriter/LoggerTraceWriter.cs
test/Microsoft.Azure.WebJobs.Logging.FunctionalTests/LoggerTest.cs

This type has gone internal in .NET Core 3. Our usage wasn't really necessary, so removing it completely in order to move Functions forward.

removing usage of FormattedLogValuesCollection

---

appveyor.yml
runtests.ps1
sample/SampleHost/SampleHost.csproj

[pack] Fixing build configuration

---

src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLoggerOptions.cs
src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Extensions/ApplicationInsightsServiceCollectionExtensions.cs
src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/QuickPulseInitializationScheduler.cs
test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ApplicationInsights/ApplicationInsightsEndToEndTests.cs

@safihamid is going to do some profiling of this before it's committed, but wanted to get the PR out for an initial look.

[AppInsights] delaying QuickPulse initialization to help with cold start
